// ============================================================
//  Romance of the Three Kingdoms - Scenario data (190 AD)
//  "The Coalition Against Dong Zhuo"
// ============================================================

const SCENARIO = {
  title: 'The Coalition Against Dong Zhuo',
  year: 190,
  month: 1,
  intro:
    'Dong Zhuo has seized the capital and holds the child Emperor hostage. ' +
    'Warlords across the land raise their banners, each dreaming of restoring ' +
    'the Han... or replacing it. Unite the realm under your rule.',
};

// x,y are positions on a 1400 x 1050 map canvas laid out to follow the real geography of Han China.
// tier: 1 = small town, 2 = city, 3 = major capital (affects starting wealth).
// The map window: an equirectangular projection of China from 100.5E to 125.5E and 42.4N to 21.1N, slightly
// compressed north-south (0.85) so the canvas keeps a 4:3-ish shape. Coastlines and rivers in js/geo.js are
// projected with the same constants by tools/buildmap.js; cities carry real-world lon/lat and an optional
// dx/dy nudge in pixels so that neighbouring labels do not overlap.
const MAP = {
  W: 1400, H: 1180, lon0: 100.5, lat1: 42.4, kx: 56, ky: 55.5,
  project(lon, lat) { return [(lon - this.lon0) * this.kx, (this.lat1 - lat) * this.ky]; },
};

// traits: regional bonuses, see TRAIT_INFO. Roads (and therefore adjacency) are defined in ROADS.
const PROVINCES = [
  // North-west and the passes
  { id: 'xiliang',     name: 'Xiliang', lon: 102.63, lat: 37.93, tier: 2, traits: ['horses'] },
  { id: 'tianshui',    name: 'Tianshui', lon: 105.72, lat: 34.58, dy: -10, tier: 2, traits: ['horses'] },
  { id: 'changan',     name: "Chang'an", lon: 108.94, lat: 34.27, tier: 3, traits: [] },
  { id: 'hongnong',    name: 'Hongnong', lon: 110.88, lat: 34.52, dy: 30, tier: 1, traits: [] },
  { id: 'luoyang',     name: 'Luoyang', lon: 112.45, lat: 34.65, dy: -10, tier: 3, traits: [] },
  { id: 'hanzhong',    name: 'Hanzhong', lon: 107.02, lat: 33.07, dy: 8, tier: 2, traits: ['grain'] },
  { id: 'shangyong',   name: 'Shangyong', lon: 110.23, lat: 32.23, dx: -8, tier: 1, traits: [] },
  // Shu and the south-west
  { id: 'zitong',      name: 'Zitong', lon: 105.16, lat: 31.64, tier: 1, traits: ['grain'] },
  { id: 'chengdu',     name: 'Chengdu', lon: 104.07, lat: 30.67, tier: 3, traits: ['grain'] },
  { id: 'jiangzhou',   name: 'Jiangzhou', lon: 106.55, lat: 29.56, tier: 1, traits: ['grain', 'river'] },
  { id: 'yongan',      name: "Yong'an", lon: 109.46, lat: 31.02, tier: 1, traits: ['river'] },
  { id: 'jianning',    name: 'Jianning', lon: 103.80, lat: 25.50, tier: 1, traits: [] },
  // North and north-east
  { id: 'jinyang',     name: 'Jinyang', lon: 112.55, lat: 37.87, tier: 1, traits: ['horses'] },
  { id: 'ye',          name: 'Ye', lon: 114.37, lat: 36.33, dx: -16, dy: -26, tier: 3, traits: [] },
  { id: 'zhongshan',   name: 'Zhongshan', lon: 114.99, lat: 38.51, dx: -16, tier: 1, traits: ['horses'] },
  { id: 'beiping',     name: 'Beiping', lon: 116.40, lat: 39.90, tier: 2, traits: ['horses'] },
  { id: 'xiangping',   name: 'Xiangping', lon: 123.17, lat: 41.27, tier: 1, traits: ['horses'] },
  { id: 'liucheng',   name: 'Liucheng', lon: 120.45, lat: 41.57, tier: 2, traits: ['horses'] },
  { id: 'danhan',     name: 'Danhan', lon: 114.88, lat: 40.82, tier: 2, traits: ['horses'] },
  { id: 'nanpi',       name: 'Nanpi', lon: 116.70, lat: 38.04, dx: 16, tier: 2, traits: ['salt', 'coast'] },
  { id: 'pingyuan',    name: 'Pingyuan', lon: 116.43, lat: 37.17, dy: 6, tier: 1, traits: ['river'] },
  { id: 'beihai',      name: 'Beihai', lon: 118.80, lat: 36.70, tier: 2, traits: ['salt', 'coast'] },
  // Central plain
  { id: 'puyang',      name: 'Puyang', lon: 115.03, lat: 35.76, dx: 18, dy: -12, tier: 2, traits: ['river'] },
  { id: 'chenliu',     name: 'Chenliu', lon: 114.30, lat: 34.80, tier: 2, traits: [] },
  { id: 'xiaopei',     name: 'Xiaopei', lon: 116.94, lat: 34.72, dx: -6, dy: -22, tier: 1, traits: [] },
  { id: 'langya',      name: 'Langya', lon: 118.35, lat: 35.05, dx: 13, dy: -8, tier: 1, traits: ['salt', 'coast'] },
  { id: 'xiapi',       name: 'Xiapi', lon: 117.95, lat: 33.91, dx: 20, dy: 24, tier: 2, traits: [] },
  { id: 'xuchang',     name: 'Xuchang', lon: 113.85, lat: 34.03, dy: 10, tier: 2, traits: [] },
  { id: 'wan',         name: 'Wan', lon: 112.53, lat: 33.00, dx: -16, tier: 2, traits: [] },
  { id: 'runan',       name: 'Runan', lon: 114.36, lat: 33.00, tier: 1, traits: [] },
  { id: 'shouchun',    name: 'Shouchun', lon: 116.78, lat: 32.58, tier: 2, traits: ['river'] },
  { id: 'lujiang',     name: 'Lujiang', lon: 116.95, lat: 31.40, tier: 1, traits: ['river'] },
  // Jing Province and the middle Yangtze
  { id: 'xinye',       name: 'Xinye', lon: 112.36, lat: 32.52, dx: 8, dy: 18, tier: 1, traits: [] },
  { id: 'xiangyang',   name: 'Xiangyang', lon: 112.15, lat: 32.05, dx: -16, dy: 36, tier: 3, traits: ['river'] },
  { id: 'jiangling',   name: 'Jiangling', lon: 112.19, lat: 30.35, tier: 3, traits: ['river', 'grain'] },
  { id: 'jiangxia',    name: 'Jiangxia', lon: 114.30, lat: 30.60, tier: 2, traits: ['river'] },
  { id: 'wuling',      name: 'Wuling', lon: 111.70, lat: 29.03, dx: -16, tier: 1, traits: [] },
  { id: 'changsha',    name: 'Changsha', lon: 112.95, lat: 28.20, dx: 10, tier: 2, traits: ['grain', 'river'] },
  { id: 'guiyang',     name: 'Guiyang', lon: 113.02, lat: 25.78, tier: 1, traits: [] },
  // Jiangdong and the lower Yangtze
  { id: 'chaisang',    name: 'Chaisang', lon: 116.00, lat: 29.70, tier: 1, traits: ['river'] },
  { id: 'yuzhang',     name: 'Yuzhang', lon: 115.90, lat: 28.68, tier: 1, traits: ['grain', 'river'] },
  { id: 'jianye',      name: 'Jianye', lon: 118.80, lat: 32.05, dy: -6, tier: 2, traits: ['river', 'coast'] },
  { id: 'wu',          name: 'Wu', lon: 120.60, lat: 31.30, dx: 8, tier: 2, traits: ['grain', 'coast', 'salt'] },
  { id: 'kuaiji',      name: 'Kuaiji', lon: 120.58, lat: 30.00, tier: 1, traits: ['coast', 'salt'] },
  // The far south
  { id: 'nanhai',      name: 'Nanhai', lon: 113.25, lat: 23.13, tier: 2, traits: ['coast', 'salt'] },
  { id: 'jiaozhi',     name: 'Jiaozhi', lon: 105.85, lat: 21.03, dy: -24, tier: 1, traits: ['grain', 'coast'] },
  // Added on the real map: the gaps in the old network
  { id: 'longxi',     name: 'Longxi',     lon: 103.85, lat: 35.40, tier: 1, traits: ['horses'] },
  { id: 'wudu',       name: 'Wudu',       lon: 105.70, lat: 33.75, tier: 1, traits: [] },
  { id: 'hedong',     name: 'Hedong',     lon: 111.00, lat: 35.10, dy: -30, tier: 1, traits: ['salt'] },
  { id: 'shangdang',  name: 'Shangdang',  lon: 113.10, lat: 36.20, dy: 24, tier: 1, traits: [] },
  { id: 'pengcheng',  name: 'Pengcheng',  lon: 117.20, lat: 34.30, tier: 2, traits: [] },
  { id: 'guangling',  name: 'Guangling',  lon: 119.40, lat: 32.40, dx: 40, dy: -40, tier: 1, traits: ['coast', 'salt'] },
  { id: 'danyang',    name: 'Danyang',    lon: 118.75, lat: 30.95, tier: 1, traits: [] },
  { id: 'lingling',   name: 'Lingling',   lon: 111.05, lat: 25.90, tier: 1, traits: ['grain'] },
  { id: 'zangke',     name: 'Zangke',     lon: 106.70, lat: 26.60, tier: 1, traits: [] },
  { id: 'hepu',       name: 'Hepu',       lon: 109.20, lat: 21.65, tier: 1, traits: ['coast', 'salt'] },
  { id: 'jianan',     name: "Jian'an",    lon: 119.30, lat: 26.08, tier: 1, traits: ['coast'] },
  { id: 'donglai',    name: 'Donglai',    lon: 121.00, lat: 37.50, tier: 1, traits: ['coast', 'salt'] },
];
for (const p of PROVINCES) { const [x, y] = MAP.project(p.lon, p.lat); p.x = Math.round(x + (p.dx || 0)); p.y = Math.round(y + (p.dy || 0)); }

// Regional traits and their effects.
const TRAIT_INFO = {
  grain:    { label: 'Granary',   desc: 'Fertile land: +25% food from agriculture.' },
  horses:   { label: 'Horse country', desc: 'Frontier cavalry: +25% recruits, and recruits arrive better trained.' },
  salt:     { label: 'Salt & trade', desc: 'Coastal salt works and markets: +20% gold income.' },
  river:    { label: 'River port', desc: 'On a great river: can build ships. Fleets decide river crossings.' },
  coast:    { label: 'Sea coast',  desc: 'On the sea: can build ships. Fleets decide sea lanes and river crossings.' },
};

// Roads: [from, to, type, waypoints]. Types: plain, pass (mountains; defenders +30%, northern passes close in winter),
// river (a great-river crossing; fleets decide), sea (a coastal sea lane; fleets decide).
const ROADS = [
  // the north-west: Hexi corridor, Tao and Wei valleys, the Long mountains
  ['xiliang', 'longxi', 'plain'],
  ['longxi', 'tianshui', 'pass'],
  ['longxi', 'wudu', 'pass'],               // over the Min mountains
  ['tianshui', 'changan', 'pass'],          // the Long pass into the Wei valley
  ['tianshui', 'wudu', 'pass'],             // Qishan: the road of the northern campaigns
  ['wudu', 'hanzhong', 'pass'],
  ['wudu', 'zitong', 'pass'],               // Yinping: the mountain track Deng Ai took
  ['changan', 'hanzhong', 'pass'],          // the Qinling trails
  ['changan', 'hongnong', 'pass'],          // Tong pass
  ['changan', 'hedong', 'river'],           // the Yellow River ford at Puban
  ['hongnong', 'luoyang', 'plain'],
  ['hedong', 'hongnong', 'river'],
  ['hedong', 'luoyang', 'river'],           // the Mengjin crossing
  ['hedong', 'jinyang', 'plain'],           // up the Fen valley
  ['hedong', 'shangdang', 'pass'],
  // the north: Taihang, the Wall and the plain beyond
  ['luoyang', 'shangdang', 'pass'],         // through Henei into the Taihang
  ['luoyang', 'ye', 'river'],
  ['luoyang', 'chenliu', 'plain'],
  ['luoyang', 'wan', 'pass'],               // through the Funiu hills into the Nanyang basin
  ['shangdang', 'jinyang', 'pass'],
  ['shangdang', 'ye', 'pass'],              // the Hukou pass, gate of the Taihang
  ['jinyang', 'zhongshan', 'pass'],         // Jingxing pass
  ['jinyang', 'danhan', 'pass'],            // Yanmen
  ['danhan', 'zhongshan', 'pass'],
  ['danhan', 'beiping', 'pass'],            // Juyong pass
  ['danhan', 'liucheng', 'plain'],          // the steppe road
  ['ye', 'zhongshan', 'plain'],
  ['ye', 'nanpi', 'plain'],
  ['ye', 'pingyuan', 'river'],
  ['ye', 'puyang', 'river'],
  ['zhongshan', 'beiping', 'plain'],
  ['zhongshan', 'nanpi', 'plain'],
  ['beiping', 'nanpi', 'plain'],
  ['beiping', 'liucheng', 'plain'],
  ['beiping', 'xiangping', 'plain'],        // the coastal corridor
  ['liucheng', 'xiangping', 'plain'],
  ['nanpi', 'pingyuan', 'plain'],
  ['pingyuan', 'puyang', 'plain'],
  ['pingyuan', 'beihai', 'plain'],
  ['beihai', 'langya', 'pass'],             // round Mount Tai
  ['beihai', 'donglai', 'plain'],           // out along the Shandong peninsula
  // the central plain and Xu
  ['puyang', 'chenliu', 'plain'],
  ['puyang', 'xiaopei', 'plain'],
  ['chenliu', 'xuchang', 'plain'],
  ['chenliu', 'xiaopei', 'plain'],
  ['xiaopei', 'pengcheng', 'plain'],
  ['pengcheng', 'xiapi', 'plain'],
  ['pengcheng', 'langya', 'plain'],
  ['pengcheng', 'shouchun', 'plain'],       // down into the Huai basin
  ['langya', 'xiapi', 'plain'],
  ['xiapi', 'shouchun', 'plain'],
  ['xiapi', 'guangling', 'plain'],          // along the Huai to the Yangtze mouth
  ['xuchang', 'wan', 'plain'],
  ['xuchang', 'runan', 'plain'],
  ['wan', 'runan', 'plain'],
  ['wan', 'xinye', 'plain'],
  ['runan', 'shouchun', 'plain'],
  ['runan', 'jiangxia', 'pass'],            // the Wusheng pass through the Dabie hills
  ['shouchun', 'lujiang', 'plain'],
  ['shouchun', 'jianye', 'river'],
  ['lujiang', 'jiangxia', 'pass'],          // the Dabie mountains
  ['lujiang', 'chaisang', 'river'],
  ['lujiang', 'jianye', 'river'],
  // Jing: the Han and the middle Yangtze
  ['shangyong', 'hanzhong', 'pass'],
  ['shangyong', 'wan', 'pass'],
  ['shangyong', 'xiangyang', 'pass'],
  ['xinye', 'xiangyang', 'river'],          // the Han at Xiangyang
  ['xiangyang', 'jiangling', 'plain'],
  ['xiangyang', 'jiangxia', 'plain'],
  ['jiangling', 'wuling', 'river'],
  ['jiangling', 'changsha', 'river'],
  ['jiangling', 'jiangxia', 'plain'],
  ['jiangling', 'yongan', 'river'],         // the Three Gorges
  ['jiangxia', 'chaisang', 'river'],
  ['jiangxia', 'changsha', 'river'],
  ['wuling', 'changsha', 'plain'],
  ['wuling', 'jiangzhou', 'pass'],          // the Wuling mountains
  ['wuling', 'lingling', 'pass'],
  ['changsha', 'lingling', 'plain'],        // up the Xiang
  ['changsha', 'guiyang', 'pass'],
  ['changsha', 'yuzhang', 'pass'],
  ['lingling', 'guiyang', 'plain'],
  ['lingling', 'zangke', 'pass'],           // west through Guilin into the hills
  ['lingling', 'nanhai', 'pass'],           // the Lingqu canal and the Xi river
  ['guiyang', 'yuzhang', 'pass'],
  ['guiyang', 'nanhai', 'pass'],            // the Meiling pass
  // Jiangdong and the lower Yangtze
  ['guangling', 'jianye', 'river'],
  ['guangling', 'wu', 'river'],
  ['jianye', 'danyang', 'plain'],
  ['jianye', 'wu', 'plain'],                // both on the south bank
  ['danyang', 'wu', 'plain'],
  ['danyang', 'kuaiji', 'pass'],
  ['danyang', 'yuzhang', 'pass'],           // through the Huizhou hills
  ['wu', 'kuaiji', 'river'],                // the Qiantang crossing
  ['kuaiji', 'jianan', 'pass'],             // the coastal mountains of Min
  ['yuzhang', 'jianan', 'pass'],            // over the Wuyi
  ['jianan', 'nanhai', 'sea'],              // the southern coast
  ['chaisang', 'yuzhang', 'plain'],
  // Shu, Nanzhong and the far south
  ['hanzhong', 'zitong', 'pass'],           // the Jinniu road
  ['zitong', 'chengdu', 'plain'],
  ['chengdu', 'jiangzhou', 'plain'],
  ['chengdu', 'jianning', 'pass'],
  ['jiangzhou', 'jianning', 'pass'],
  ['jiangzhou', 'yongan', 'river'],         // down the Yangtze
  ['jiangzhou', 'zangke', 'pass'],
  ['jianning', 'zangke', 'pass'],
  ['jianning', 'jiaozhi', 'pass'],          // down the Red River
  ['nanhai', 'hepu', 'sea'],
  ['hepu', 'jiaozhi', 'sea'],               // the Gulf of Tonkin
];

// Cities on the lower Yellow River, exposed to summer floods.
const FLOOD_PLAIN = ['puyang', 'pingyuan', 'chenliu', 'xiaopei', 'ye', 'nanpi'];

// Faction definitions. `aggr` scales AI aggression (1 = normal). `persona` traits: schemer (recruits prisoners,
// gambles on stratagems), honourable (keeps treaties, releases prisoners), treacherous (breaks treaties, executes),
// cautious (defends, accepts peace), reckless (attacks early), builder (develops and fortifies).
const FACTIONS = [
  { id: 'caocao',     name: 'Cao Cao',     ruler: 'Cao Cao',     color: '#3b6fd6', aggr: 1.3, cities: ['chenliu'],              persona: ['schemer'], blurb: 'A brilliant, ruthless tactician with a loyal clan of generals.' },
  { id: 'liubei',     name: 'Liu Bei',     ruler: 'Liu Bei',     color: '#3fa34d', aggr: 0.9, cities: ['pingyuan'],             wanderer: true, persona: ['honourable'], blurb: 'A humble but charismatic scion of the Han, sworn brother to Guan Yu and Zhang Fei.' },
  { id: 'sunjian',    name: 'Sun Jian',    ruler: 'Sun Jian',    color: '#d63b3b', aggr: 1.2, cities: ['changsha', 'lingling'],             wanderer: true, persona: ['reckless'], blurb: 'The Tiger of Jiangdong. Ferocious in battle, with a promising heir.' },
  { id: 'yuanshao',   name: 'Yuan Shao',   ruler: 'Yuan Shao',   color: '#f2e394', aggr: 1.0, cities: ['ye', 'nanpi'],          persona: ['cautious', 'builder'], blurb: 'Head of the most prestigious family in the empire. Wealthy and well-served.' },
  { id: 'dongzhuo',   name: 'Dong Zhuo',   ruler: 'Dong Zhuo',   color: '#3a3a3a', aggr: 1.4, cities: ['luoyang', 'changan', 'hongnong', 'hedong'],   emperor: true, persona: ['treacherous'], blurb: 'The tyrant who holds the Emperor. Commands Lü Bu, the mightiest warrior alive.' },
  { id: 'yuanshu',    name: 'Yuan Shu',    ruler: 'Yuan Shu',     color: '#e67e22', aggr: 1.1, cities: ['wan', 'shouchun'],      persona: ['treacherous'], blurb: "Yuan Shao's arrogant half-brother. Rich lands, mediocre officers." },
  { id: 'liubiao',    name: 'Liu Biao',    ruler: 'Liu Biao',    color: '#16a085', aggr: 0.6, cities: ['xiangyang', 'jiangxia', 'jiangling', 'xinye'], persona: ['cautious', 'builder'], blurb: 'A cautious scholar-lord of Jing Province. Strong defenses, veteran generals.' },
  { id: 'liuzhang',   name: 'Liu Zhang',   ruler: 'Liu Zhang',   color: '#b8860b', aggr: 0.5, cities: ['chengdu', 'jiangzhou', 'zitong', 'yongan'], persona: ['cautious'], blurb: 'Weak-willed ruler of the fertile, isolated lands of Shu.' },
  { id: 'mateng',     name: 'Ma Teng',     ruler: 'Ma Teng',     color: '#8d5524', aggr: 1.1, cities: ['xiliang', 'tianshui', 'longxi'],           persona: ['reckless'], blurb: 'Lord of the frontier cavalry. His son Ma Chao is a rising terror.' },
  { id: 'gongsunzan', name: 'Gongsun Zan', ruler: 'Gongsun Zan', color: '#cfd8dc', aggr: 1.0, cities: ['beiping'],              persona: ['reckless'], blurb: 'Northern border general with the White Horse cavalry and young Zhao Yun.' },
  { id: 'taoqian',    name: 'Tao Qian',    ruler: 'Tao Qian',    color: '#e991b8', aggr: 0.5, cities: ['xiapi', 'langya', 'pengcheng'],                persona: ['honourable', 'builder'], blurb: 'Elderly, benevolent governor of Xu. Rich but poorly defended.' },
  { id: 'zhangchao',  name: 'Zhang Chao',  ruler: 'Zhang Chao',  color: '#556b2f', aggr: 0.6, cities: ['guangling'],                                    persona: ['honourable', 'cautious'], blurb: 'Administrator of Guangling and a lord of the coalition. One city on the coast, and in Zang Hong a follower loyal to the death.' },
  { id: 'kongrong',   name: 'Kong Rong',   ruler: 'Kong Rong',   color: '#5dade2', aggr: 0.4, cities: ['beihai'],               persona: ['honourable', 'builder'], blurb: 'A famous Confucian scholar. No general himself, but Taishi Ci serves him.' },
  { id: 'zhanglu',    name: 'Zhang Lu',    ruler: 'Zhang Lu',    color: '#7f8c5a', aggr: 0.5, cities: ['hanzhong'],             persona: ['builder'], blurb: 'Theocratic ruler of Hanzhong, leader of the Five Pecks of Rice sect.' },
  { id: 'liuyao',     name: 'Liu Yao',     ruler: 'Liu Yao',     color: '#f1948a', aggr: 0.6, cities: ['wu', 'jianye'],                   persona: ['cautious'], blurb: 'Imperial clansman holding the rich lands south of the Yangtze.' },
  { id: 'wanglang',   name: 'Wang Lang',   ruler: 'Wang Lang',   color: '#5b5ea6', aggr: 0.4, cities: ['kuaiji'],               persona: ['builder'], blurb: 'A learned administrator in the far southeast.' },
  { id: 'shixie',     name: 'Shi Xie',     ruler: 'Shi Xie',     color: '#82c46c', aggr: 0.3, cities: ['jiaozhi', 'nanhai', 'hepu'],              persona: ['builder', 'cautious'], blurb: 'Isolated but stable lord of the deep south.' },
  { id: 'gongsundu',  name: 'Gongsun Du',  ruler: 'Gongsun Du',  color: '#9b7bb5', aggr: 0.5, cities: ['xiangping'],            persona: ['cautious'], blurb: 'Self-made warlord of distant Liaodong, beyond the reach of the court.' },
  { id: 'liudai',     name: 'Liu Dai',     ruler: 'Liu Dai',     color: '#c71585', aggr: 0.7, cities: ['puyang'],               persona: ['honourable'], blurb: 'Inspector of Yan Province and a coalition lord, holding the Yellow River crossings with few men of note.' },
  { id: 'zhangyang',  name: 'Zhang Yang',  ruler: 'Zhang Yang',  color: '#00ced1', aggr: 0.8, cities: ['jinyang', 'shangdang'],              persona: ['reckless'], blurb: 'A rough frontier soldier who made himself master of Bing Province after its governor was murdered.' },
  { id: 'zhangyan',   name: 'Zhang Yan',   ruler: 'Zhang Yan',   color: '#5a1e1e', aggr: 1.5, cities: ['zhongshan'],            persona: ['treacherous', 'reckless'], blurb: 'Chief of the Black Mountain bandits of the Taihang. A vast, undisciplined host that raids rather than rules.' },
  { id: 'lukang',     name: 'Lu Kang',     ruler: 'Lu Kang',     color: '#f5deb3', aggr: 0.3, cities: ['lujiang'],              persona: ['honourable', 'cautious'], blurb: 'An aged Han loyalist administrator, stubborn behind the walls of Lujiang.' },
  { id: 'menghuo',    name: 'Meng Huo',    ruler: 'Meng Huo',    color: '#7b1fa2', aggr: 1.2, cities: ['jianning'],             persona: ['reckless'], blurb: 'King of the Nanman tribes of the south-west. Fierce warriors and war elephants, but no administrators.' },
  { id: 'wuhuan',     name: 'Tadun',       ruler: 'Tadun',       color: '#708090', aggr: 1.6, cities: ['liucheng'],             raider: true, playable: false, persona: ['treacherous', 'reckless'], blurb: 'Tadun, great chieftain of the Wuhuan. His riders sack the border towns for grain and gold and vanish back into the steppe.' },
  { id: 'xianbei',    name: 'Kebineng',    ruler: 'Kebineng',    color: '#bdb76b', aggr: 1.6, cities: ['danhan'],               raider: true, playable: false, persona: ['treacherous', 'reckless'], blurb: 'Kebineng, rising chieftain of the Xianbei. From the steppe beyond the Wall his horsemen fall on Bing and You provinces every summer.' },
];

// Officers: [name, LDR, WAR, INT, POL, CHR, faction (null = free), city, loyalty, birth year]
const OFFICERS = [
  // Cao Cao
  ['Cao Cao',      96, 72, 91, 94, 96, 'caocao', 'chenliu', 100, 155],
  ['Xiahou Dun',   89, 90, 55, 60, 74, 'caocao', 'chenliu', 95, 157],
  ['Xiahou Yuan',  85, 88, 52, 48, 70, 'caocao', 'chenliu', 95, 160],
  ['Cao Ren',      88, 84, 62, 60, 70, 'caocao', 'chenliu', 95, 168],
  ['Cao Hong',     76, 82, 40, 45, 60, 'caocao', 'chenliu', 92, 165],
  ['Xun Yu',       68, 40, 95, 99, 88, 'caocao', 'chenliu', 90, 163],
  ['Yue Jin',      80, 84, 45, 40, 62, 'caocao', 'chenliu', 85, 165],
  ['Li Dian',      78, 79, 74, 70, 68, 'caocao', 'chenliu', 85, 174],
  // Liu Bei
  ['Liu Bei',      78, 70, 74, 82, 99, 'liubei', 'pingyuan', 100, 161],
  ['Guan Yu',      95, 97, 75, 62, 92, 'liubei', 'pingyuan', 100, 160],
  ['Zhang Fei',    88, 98, 30, 22, 45, 'liubei', 'pingyuan', 100, 167],
  ['Jian Yong',    45, 35, 78, 80, 74, 'liubei', 'pingyuan', 85, 160],
  ['Sun Qian',     40, 30, 76, 82, 70, 'liubei', 'pingyuan', 82, 160],
  // Sun Jian
  ['Sun Jian',     92, 90, 69, 68, 87, 'sunjian', 'changsha', 100, 155],
  ['Sun Ce',       90, 92, 68, 60, 88, 'sunjian', 'changsha', 100, 175],
  ['Huang Gai',    82, 83, 65, 60, 68, 'sunjian', 'changsha', 92, 150],
  ['Cheng Pu',     84, 80, 74, 70, 72, 'sunjian', 'changsha', 92, 150],
  ['Han Dang',     75, 79, 50, 42, 55, 'sunjian', 'changsha', 88, 160],
  ['Zhu Zhi',      72, 65, 72, 74, 70, 'sunjian', 'changsha', 85, 156],
  // Yuan Shao
  ['Yuan Shao',    82, 70, 68, 76, 90, 'yuanshao', 'ye', 100, 154],
  ['Yan Liang',    84, 93, 30, 25, 40, 'yuanshao', 'ye', 88, 160],
  ['Wen Chou',     82, 92, 28, 22, 38, 'yuanshao', 'nanpi', 88, 160],
  ['Tian Feng',    60, 35, 92, 78, 55, 'yuanshao', 'ye', 80, 150],
  ['Ju Shou',      68, 40, 90, 82, 60, 'yuanshao', 'ye', 82, 155],
  ['Guo Tu',       50, 30, 78, 70, 58, 'yuanshao', 'nanpi', 78, 160],
  ['Zhang He',     90, 89, 70, 60, 68, 'yuanshao', 'nanpi', 75, 165],
  ['Gao Lan',      76, 80, 45, 40, 50, 'yuanshao', 'ye', 78, 165],
  // Dong Zhuo
  ['Dong Zhuo',    85, 84, 60, 20, 25, 'dongzhuo', 'luoyang', 100, 139],
  ['Lü Bu',        92, 100, 26, 13, 40, 'dongzhuo', 'luoyang', 55, 160],
  ['Li Ru',        70, 30, 93, 82, 30, 'dongzhuo', 'luoyang', 90, 150],
  ['Hua Xiong',    80, 90, 30, 20, 35, 'dongzhuo', 'luoyang', 85, 160],
  ['Zhang Liao',   92, 92, 78, 58, 78, 'dongzhuo', 'luoyang', 65, 169],
  ['Li Jue',       75, 78, 40, 30, 20, 'dongzhuo', 'changan', 80, 155],
  ['Guo Si',       72, 76, 38, 28, 22, 'dongzhuo', 'changan', 80, 155],
  ['Xu Rong',      78, 80, 62, 50, 45, 'dongzhuo', 'hongnong', 82, 155],
  ['Fan Chou',     68, 74, 30, 25, 30, 'dongzhuo', 'changan', 78, 160],
  // Yuan Shu
  ['Yuan Shu',     62, 60, 50, 45, 45, 'yuanshu', 'wan', 100, 155],
  ['Ji Ling',      78, 85, 45, 40, 50, 'yuanshu', 'wan', 85, 160],
  ['Zhang Xun',    68, 70, 50, 45, 48, 'yuanshu', 'shouchun', 80, 160],
  ['Yang Hong',    50, 35, 76, 74, 55, 'yuanshu', 'wan', 78, 160],
  ['Yan Xiang',    55, 40, 74, 76, 60, 'yuanshu', 'shouchun', 78, 160],
  // Liu Biao
  ['Liu Biao',     68, 40, 74, 80, 78, 'liubiao', 'xiangyang', 100, 142],
  ['Huang Zhong',  86, 94, 60, 52, 72, 'liubiao', 'xiangyang', 80, 148],
  ['Cai Mao',      74, 72, 60, 62, 55, 'liubiao', 'xinye', 88, 160],
  ['Kuai Liang',   50, 30, 82, 84, 65, 'liubiao', 'xiangyang', 88, 155],
  ['Kuai Yue',     52, 32, 86, 82, 60, 'liubiao', 'jiangling', 88, 158],
  ['Wen Ping',     80, 82, 58, 55, 62, 'liubiao', 'jiangxia', 85, 165],
  ['Wei Yan',      85, 90, 55, 48, 40, 'liubiao', 'jiangxia', 60, 174],
  // Liu Zhang
  ['Liu Zhang',    40, 30, 45, 60, 68, 'liuzhang', 'chengdu', 100, 162],
  ['Zhang Ren',    82, 86, 62, 50, 60, 'liuzhang', 'chengdu', 90, 165],
  ['Yan Yan',      80, 84, 65, 58, 62, 'liuzhang', 'jiangzhou', 85, 145],
  ['Huang Quan',   68, 55, 82, 80, 65, 'liuzhang', 'chengdu', 85, 170],
  ['Fa Zheng',     60, 45, 92, 78, 55, 'liuzhang', 'chengdu', 60, 176],
  ['Li Yan',       78, 80, 70, 74, 60, 'liuzhang', 'jiangzhou', 70, 170],
  ['Wu Yi',        74, 76, 60, 62, 58, 'liuzhang', 'zitong', 80, 170],
  ['Zhao Wei',      62, 64, 50, 52, 45, 'liuzhang', 'yongan', 60, 165],
  // Ma Teng
  ['Ma Teng',      84, 88, 45, 40, 70, 'mateng', 'xiliang', 100, 156],
  ['Ma Chao',      88, 96, 44, 30, 78, 'mateng', 'xiliang', 100, 176],
  ['Pang De',      85, 92, 58, 50, 60, 'mateng', 'xiliang', 88, 170],
  ['Ma Dai',       78, 80, 62, 55, 65, 'mateng', 'xiliang', 95, 178],
  ['Han Sui',      76, 72, 68, 62, 55, 'mateng', 'longxi', 60, 145],
  // Gongsun Zan
  ['Gongsun Zan',  82, 80, 50, 45, 70, 'gongsunzan', 'beiping', 100, 150],
  ['Zhao Yun',     92, 96, 78, 68, 85, 'gongsunzan', 'beiping', 70, 168],
  ['Yan Gang',     60, 68, 30, 30, 40, 'gongsunzan', 'beiping', 82, 160],
  ['Tian Yu',      70, 65, 78, 76, 62, 'gongsunzan', 'beiping', 78, 171],
  // Tao Qian
  ['Tao Qian',     55, 40, 62, 74, 72, 'taoqian', 'xiapi', 100, 132],
  ['Zhang Chao',   58, 52, 66, 70, 68, 'zhangchao', 'guangling', 100, 150],
  ['Zang Hong',    72, 58, 78, 80, 84, 'zhangchao', 'guangling', 96, 160],
  ['Cao Bao',      60, 68, 40, 35, 40, 'taoqian', 'xiapi', 70, 155],
  ['Mi Zhu',       40, 30, 76, 88, 82, 'taoqian', 'xiapi', 75, 165],
  ['Chen Deng',    65, 50, 85, 82, 70, 'taoqian', 'xiapi', 72, 170],
  // Kong Rong
  ['Kong Rong',    40, 25, 78, 76, 88, 'kongrong', 'beihai', 100, 153],
  ['Taishi Ci',    88, 93, 66, 58, 75, 'kongrong', 'beihai', 65, 166],
  ['Wang Xiu',     45, 35, 72, 78, 62, 'kongrong', 'beihai', 85, 160],
  // Zhang Lu
  ['Zhang Lu',     52, 40, 70, 72, 76, 'zhanglu', 'hanzhong', 100, 160],
  ['Yang Ang',     60, 68, 35, 30, 40, 'zhanglu', 'hanzhong', 80, 160],
  ['Yan Pu',       45, 30, 78, 76, 55, 'zhanglu', 'hanzhong', 82, 165],
  // Liu Yao
  ['Liu Yao',      50, 38, 60, 66, 70, 'liuyao', 'wu', 100, 156],
  ['Zhang Ying',   62, 70, 40, 38, 45, 'liuyao', 'jianye', 78, 160],
  ['Fan Neng',     58, 72, 30, 28, 35, 'liuyao', 'wu', 75, 160],
  // Wang Lang
  ['Wang Lang',    40, 30, 80, 82, 70, 'wanglang', 'kuaiji', 100, 152],
  ['Yu Fan',       52, 40, 84, 78, 55, 'wanglang', 'kuaiji', 70, 164],
  ['Zhou Xin',     58, 64, 45, 40, 42, 'wanglang', 'kuaiji', 78, 160],
  // Shi Xie
  ['Shi Xie',      50, 35, 74, 80, 76, 'shixie', 'jiaozhi', 100, 137],
  ['Shi Yi',        55, 50, 60, 66, 60, 'shixie', 'nanhai', 90, 145],
  // Gongsun Du
  ['Gongsun Du',    70, 68, 50, 55, 55, 'gongsundu', 'xiangping', 100, 150],
  ['Gongsun Kang',  65, 68, 50, 56, 55, 'gongsundu', 'xiangping', 95, 172],
  // Liu Dai
  ['Liu Dai',       62, 55, 62, 70, 66, 'liudai', 'puyang', 100, 160],
  ['Wang Gong',     55, 52, 60, 65, 50, 'liudai', 'puyang', 85, 155],
  // Zhang Yang
  ['Zhang Yang',    68, 72, 45, 42, 55, 'zhangyang', 'jinyang', 100, 155],
  ['Yang Chou',     58, 66, 40, 35, 30, 'zhangyang', 'jinyang', 45, 160],
  // Zhang Yan (Black Mountain bandits)
  ['Zhang Yan',     78, 82, 40, 25, 55, 'zhangyan', 'zhongshan', 100, 160],
  ['Du Chang',      60, 70, 30, 20, 35, 'zhangyan', 'zhongshan', 80, 160],
  // Lu Kang
  ['Lu Kang',       60, 45, 72, 80, 74, 'lukang', 'lujiang', 100, 126],
  ['Lu Jun',        55, 50, 65, 70, 60, 'lukang', 'lujiang', 95, 160],
  // Meng Huo (Nanman)
  ['Meng Huo',      78, 84, 30, 25, 60, 'menghuo', 'jianning', 100, 160],
  ['Zhu Rong',      70, 82, 40, 30, 60, 'menghuo', 'jianning', 100, 165],
  ['Meng You',      62, 74, 30, 25, 45, 'menghuo', 'jianning', 95, 163],
  // Tadun (Wuhuan nomads)
  ['Tadun',         82, 88, 40, 20, 65, 'wuhuan', 'liucheng', 100, 160],
  ['Louban',        60, 70, 30, 20, 45, 'wuhuan', 'liucheng', 90, 175],
  ['Supuyan',       65, 72, 35, 25, 40, 'wuhuan', 'liucheng', 85, 165],
  // Kebineng (Xianbei nomads)
  ['Kebineng',      85, 86, 55, 40, 70, 'xianbei', 'danhan', 100, 168],
  ['Budugen',       70, 76, 35, 30, 50, 'xianbei', 'danhan', 90, 172],
  ['Fuluohan',      66, 72, 30, 28, 45, 'xianbei', 'danhan', 85, 170],
  // Free officers (scattered across the land)
  ['Xu Huang',     88, 90, 60, 45, 60, null, 'jinyang', 0, 169],
  ['Zhou Yu',      92, 70, 96, 80, 95, null, 'chaisang', 0, 175],
  ['Lu Su',        78, 55, 88, 88, 84, null, 'chaisang', 0, 172],
  ['Xu Shu',       76, 62, 90, 76, 70, null, 'xuchang', 0, 170],
  ['Zhang Xiu',    74, 76, 48, 42, 55, null, 'xuchang', 0, 165],
  ['Guo Jia',      45, 20, 98, 68, 76, null, 'ye', 0, 170],
  ['Xun You',      65, 45, 95, 84, 70, null, 'luoyang', 0, 157],
  ['Jia Xu',       70, 45, 97, 82, 50, null, 'changan', 0, 147],
  ['Zang Ba',       76, 78, 40, 35, 45, 'taoqian', 'langya', 70, 165],
  ['Gan Ning',     86, 92, 58, 40, 60, null, 'jiangzhou', 0, 170],
  ['Ling Cao',     62, 70, 30, 30, 40, null, 'wu', 0, 160],
  ['Zhang Zhao',   40, 25, 84, 96, 78, null, 'wu', 0, 156],
  ['Dian Wei',     60, 100, 20, 15, 40, null, 'chenliu', 0, 160],
  ['Xu Chu',       65, 98, 30, 22, 50, null, 'runan', 0, 170],
  ['Chen Gong',    60, 45, 88, 74, 55, null, 'puyang', 0, 160],
  ['Zhang Song',   35, 20, 86, 80, 30, null, 'chengdu', 0, 170],
  ['Hua Xin',      45, 30, 76, 84, 60, null, 'kuaiji', 0, 157],
  ['Yuan Tan',     60, 62, 45, 42, 50, null, 'beihai', 0, 172],
  ['Liu Pi',       55, 62, 30, 28, 45, null, 'runan', 0, 160],
];

// Starting relations between houses (-100 hostile .. 100 close). Unlisted pairs start at 0.
const INITIAL_RELATIONS = [
  ['zhangchao', 'caocao', 20], ['zhangchao', 'taoqian', 15], ['zhangchao', 'yuanshu', -25], ['zhangchao', 'dongzhuo', -40], ['zhangyang', 'dongzhuo', -30],
  ['yuanshao', 'yuanshu', -40],
  ['caocao', 'yuanshao', 25],
  ['liubei', 'gongsunzan', 35],
  ['sunjian', 'yuanshu', 15],
  ['sunjian', 'liubiao', -30],
  ['liubei', 'taoqian', 20],
  ['liubei', 'kongrong', 20],
  ['gongsunzan', 'yuanshao', -30],
  ['liuzhang', 'zhanglu', -35],
  ['mateng', 'dongzhuo', -30],
  ['caocao', 'dongzhuo', -50],
  ['yuanshao', 'dongzhuo', -50],
  ['sunjian', 'dongzhuo', -50],
  ['liubei', 'dongzhuo', -40],
  ['yuanshu', 'dongzhuo', -40],
  ['kongrong', 'dongzhuo', -40],
  ['taoqian', 'dongzhuo', -30],
  ['liubiao', 'dongzhuo', -30],
  ['gongsundu', 'gongsunzan', -25],
  ['gongsundu', 'yuanshao', -10],
  ['liudai', 'caocao', 20],
  ['liudai', 'dongzhuo', -40],
  ['liudai', 'yuanshao', 10],
  ['zhangyang', 'dongzhuo', -20],
  ['zhangyang', 'yuanshao', 10],
  ['zhangyan', 'yuanshao', -40],
  ['zhangyan', 'gongsunzan', 20],
  ['zhangyan', 'liudai', -20],
  ['lukang', 'yuanshu', -25],
  ['lukang', 'sunjian', -10],
  ['menghuo', 'liuzhang', -35],
  ['menghuo', 'shixie', -10],
  ['wuhuan', 'gongsunzan', -40],
  ['wuhuan', 'gongsundu', -30],
  ['wuhuan', 'yuanshao', 10],
  ['xianbei', 'wuhuan', -20],
  ['xianbei', 'gongsunzan', -30],
  ['xianbei', 'zhangyang', -20],
  ['xianbei', 'zhangyan', -10],
  ['xianbei', 'yuanshao', -10],
];

// Officers who come of age or come forward after 190: [name, LDR, WAR, INT, POL, CHR, born, appears, city, preferred house].
// They appear in the city as free talents, or join the preferred house at once if it still lives and holds a city.
const LATER_OFFICERS = [
  ['Yu Jin',               80,  78,  55,  50,  55, 160, 192, 'chenliu',    'caocao'],
  ['Man Chong',            70,  60,  82,  84,  65, 165, 193, 'xuchang',    'caocao'],
  ['Zhong Yao',            55,  40,  80,  88,  70, 151, 194, 'changan',    null],
  ['Zhou Tai',             78,  86,  50,  42,  60, 168, 194, 'lujiang',    'sunjian'],
  ['Jiang Qin',            72,  78,  48,  40,  55, 165, 194, 'lujiang',    'sunjian'],
  ['Chen Wu',              70,  80,  40,  35,  50, 168, 195, 'chaisang',   'sunjian'],
  ['Dong Xi',              72,  84,  45,  38,  52, 170, 196, 'jianye',     'sunjian'],
  ['Liao Hua',             70,  72,  55,  50,  55, 176, 197, 'xiangyang',  null],
  ['Chen Dao',             76,  80,  50,  45,  55, 170, 198, 'runan',      'liubei'],
  ['Zhuge Jin',            60,  40,  82,  86,  78, 174, 199, 'jianye',     'sunjian'],
  ['Bu Zhi',               66,  50,  78,  84,  70, 172, 199, 'wu',         'sunjian'],
  ['Gu Yong',              50,  30,  80,  92,  74, 168, 199, 'wu',         'sunjian'],
  ['Chen Qun',             55,  35,  84,  94,  72, 168, 200, 'xiapi',      'caocao'],
  ['Pan Zhang',            70,  82,  40,  36,  45, 170, 200, 'kuaiji',     'sunjian'],
  ['Xu Sheng',             78,  80,  60,  55,  60, 176, 200, 'wu',         'sunjian'],
  ['Zhu Ran',              80,  78,  65,  58,  62, 182, 201, 'wu',         'sunjian'],
  ['Ma Liang',             52,  35,  84,  82,  76, 187, 203, 'xiangyang',  'liubei'],
  ['Lu Xun',               92,  74,  95,  88,  84, 183, 203, 'wu',         'sunjian'],
  ['Cao Pi',               72,  66,  80,  86,  70, 187, 204, 'chenliu',    'caocao'],
  ['Cao Zhen',             82,  80,  62,  60,  60, 185, 205, 'chenliu',    'caocao'],
  ['Cao Xiu',              78,  82,  52,  50,  55, 183, 205, 'xuchang',    'caocao'],
  ['Zhu Huan',             80,  82,  68,  55,  60, 177, 205, 'jianye',     'sunjian'],
  ['Pang Tong',            62,  30,  97,  85,  70, 179, 205, 'xiangyang',  null],
  ['Guan Ping',            74,  80,  55,  50,  62, 178, 205, 'xinye',      'liubei'],
  ['Liu Feng',             68,  76,  48,  45,  50, 185, 205, 'xinye',      'liubei'],
  ['Jia Kui',              70,  55,  80,  82,  60, 174, 206, 'hongnong',   'caocao'],
  ['Ling Tong',            76,  84,  55,  48,  60, 189, 206, 'jianye',     'sunjian'],
  ['Cao Zhang',            82,  91,  40,  35,  55, 189, 207, 'ye',         'caocao'],
  ['Sima Yi',              90,  62,  98,  95,  78, 179, 208, 'xuchang',    'caocao'],
  ['Huo Jun',              76,  72,  68,  62,  58, 178, 208, 'xiangyang',  'liubei'],
  ['Zhao Lei',             70,  74,  50,  45,  45, 182, 208, 'jiangling',  null],
  ['Xiahou Shang',         74,  76,  58,  55,  58, 186, 209, 'xuchang',    'caocao'],
  ['Ma Su',                45,  30,  86,  76,  65, 190, 210, 'xiangyang',  'liubei'],
  ['Guo Huai',             84,  72,  82,  70,  62, 187, 210, 'changan',    'caocao'],
  ['Cao Zhi',              40,  25,  88,  70,  80, 192, 210, 'ye',         'caocao'],
  ['Jiang Wan',            58,  30,  82,  92,  74, 178, 211, 'jiangzhou',  'liubei'],
  ['Wu Ban',               74,  78,  50,  45,  50, 180, 211, 'chengdu',    'liuzhang'],
  ['Zhang Yi',             76,  78,  60,  55,  52, 186, 212, 'chengdu',    'liuzhang'],
  ['Fei Yi',               62,  40,  86,  90,  82, 189, 214, 'jiangzhou',  'liubei'],
  ['Ma Zhong',             78,  76,  66,  60,  60, 185, 214, 'zitong',     'liuzhang'],
  ['Wang Ping',            84,  80,  60,  52,  50, 183, 215, 'hanzhong',   null],
  ['Quan Cong',            78,  74,  66,  60,  62, 198, 216, 'wu',         'sunjian'],
  ['Hao Zhao',             82,  80,  70,  55,  50, 186, 216, 'changan',    'caocao'],
  ['Zhang Ni',             78,  82,  55,  48,  52, 190, 217, 'jiangzhou',  null],
  ['Ding Feng',            78,  84,  60,  48,  55, 195, 218, 'kuaiji',     'sunjian'],
  ['Wang Shuang',          74,  88,  35,  30,  40, 192, 219, 'tianshui',   'caocao'],
  ['Guan Xing',            76,  84,  58,  50,  62, 200, 219, 'jiangling',  'liubei'],
  ['Zhang Bao',            74,  86,  40,  35,  50, 201, 219, 'jiangling',  'liubei'],
  ['Jiang Wei',            90,  82,  92,  80,  78, 202, 220, 'tianshui',   null],
  ['Deng Ai',              94,  84,  90,  70,  55, 197, 222, 'xuchang',    'caocao'],
  ['Zhu Ju',               70,  65,  72,  74,  62, 194, 222, 'jianye',     'sunjian'],
  ['Zhuge Ke',             72,  60,  84,  70,  58, 203, 223, 'jianye',     'sunjian'],
  ['Zhang Yi (Shu)',       72,  78,  55,  50,  50, 196, 224, 'chengdu',    'liubei'],
  ['Wang Jun',             80,  70,  78,  74,  60, 206, 226, 'hongnong',   'caocao'],
  ['Sima Shi',             80,  60,  88,  90,  66, 208, 228, 'xuchang',    'caocao'],
  ['Sima Zhao',            78,  58,  90,  92,  64, 211, 230, 'xuchang',    'caocao'],
  ['Lu Kang (Wu)',         84,  70,  88,  82,  74, 226, 244, 'jianye',     'sunjian'],
  ['Zhong Hui',            76,  58,  92,  78,  56, 225, 245, 'changan',    'caocao'],
  ['Zhuge Zhan',           68,  55,  80,  78,  72, 227, 246, 'chengdu',    'liubei'],
  ['Ding Feng (junior)',   66,  76,  50,  45,  50, 220, 240, 'wu',         'sunjian'],
  // lesser figures who fill out the courts of the age
  ['Sun Jing',             66,  60,  58,  62,  62, 155, 191, 'changsha',   'sunjian'],
  ['Zhang Hong',           50,  30,  82,  86,  74, 153, 195, 'jianye',     'sunjian'],
  ['Lu Fan',               62,  55,  70,  78,  60, 160, 194, 'wu',         'sunjian'],
  ['He Qi',                78,  80,  58,  50,  55, 170, 196, 'kuaiji',     'sunjian'],
  ['Wu Can',               55,  40,  74,  80,  62, 172, 200, 'wu',         'sunjian'],
  ['Yan Jun',              48,  30,  78,  80,  66, 170, 200, 'wu',         'sunjian'],
  ['Sun Yu',               64,  60,  62,  66,  60, 177, 200, 'jianye',     'sunjian'],
  ['Lu Dai',               70,  68,  62,  64,  55, 161, 205, 'yuzhang',    'sunjian'],
  ['Sun Huan',             72,  74,  56,  50,  58, 194, 218, 'jianye',     'sunjian'],
  ['Zhou Fang',            62,  58,  78,  70,  60, 185, 220, 'yuzhang',    'sunjian'],
  ['Mi Fang',              55,  58,  50,  62,  45, 168, 194, 'xiapi',      'liubei'],
  ['Yi Ji',                50,  35,  76,  80,  70, 165, 200, 'xiangyang',  'liubiao'],
  ['Xiang Lang',           52,  40,  74,  82,  66, 167, 205, 'xiangyang',  'liubei'],
  ['Deng Zhi',             68,  62,  74,  78,  76, 178, 214, 'chengdu',    'liubei'],
  ['Wu Lan',               66,  72,  40,  38,  45, 170, 212, 'chengdu',    'liuzhang'],
  ['Lei Tong',             62,  74,  35,  30,  42, 172, 212, 'jiangzhou',  'liuzhang'],
  ['Yang Yi',              48,  30,  76,  80,  40, 185, 214, 'chengdu',    'liubei'],
  ['Dong Yun',             50,  30,  78,  88,  72, 190, 220, 'chengdu',    'liubei'],
  ['Cao Ang',              66,  68,  55,  58,  62, 172, 190, 'chenliu',    'caocao'],
  ['Cao Chun',             76,  78,  55,  50,  58, 170, 190, 'chenliu',    'caocao'],
  ['Xiahou En',            55,  66,  30,  30,  40, 175, 195, 'xuchang',    'caocao'],
  ['Han Hao',              70,  64,  66,  72,  58, 165, 196, 'xuchang',    'caocao'],
  ['Shi Huan',             68,  72,  45,  40,  48, 168, 196, 'xuchang',    'caocao'],
  ['Li Tong',              74,  80,  48,  45,  55, 168, 197, 'runan',      'caocao'],
  ['Liu Ye',               45,  30,  84,  80,  60, 170, 200, 'xuchang',    'caocao'],
  ['Jiang Ji',             50,  35,  82,  84,  62, 175, 205, 'xuchang',    'caocao'],
  ['Dong Zhao',            48,  30,  80,  84,  62, 156, 195, 'jinyang',    'zhangyang'],
  ['Wang Can',             30,  15,  78,  70,  68, 177, 205, 'xiangyang',  'liubiao'],
  ['Zhang Yun',            60,  60,  50,  52,  45, 165, 195, 'xiangyang',  'liubiao'],
  ['Huang Zu',             66,  68,  40,  42,  40, 160, 190, 'jiangxia',   'liubiao'],
  ['Han Xuan',             55,  50,  40,  55,  30, 160, 200, 'changsha',   'liubiao'],
  ['Jin Xuan',             58,  62,  42,  48,  45, 165, 200, 'wuling',     'liubiao'],
  ['Zhao Fan',             50,  45,  55,  60,  55, 168, 200, 'guiyang',    'liubiao'],
  ['Xing Daorong',         55,  76,  25,  20,  30, 170, 200, 'guiyang',    'liubiao'],
  ['Shen Pei',             60,  45,  76,  80,  55, 160, 191, 'ye',         'yuanshao'],
  ['Feng Ji',              45,  30,  74,  66,  40, 158, 191, 'ye',         'yuanshao'],
  ['Xu You',               40,  25,  80,  60,  45, 155, 191, 'ye',         'yuanshao'],
  ['Chunyu Qiong',         62,  70,  35,  30,  40, 155, 190, 'ye',         'yuanshao'],
  ['Qu Yi',                78,  84,  50,  40,  45, 160, 191, 'ye',         'yuanshao'],
  ['Cui Yan',              55,  40,  78,  86,  76, 163, 199, 'ye',         'yuanshao'],
  ['Xin Pi',               50,  35,  80,  82,  64, 168, 200, 'ye',         'yuanshao'],
  ['Han Meng',             64,  72,  40,  35,  42, 165, 195, 'nanpi',      'yuanshao'],
  ['Lei Bo',               58,  66,  35,  30,  40, 165, 195, 'shouchun',   'yuanshu'],
  ['Chen Lan',             60,  68,  32,  30,  38, 165, 195, 'shouchun',   'yuanshu'],
  ['Qiao Rui',             62,  66,  44,  40,  45, 158, 190, 'wan',        'yuanshu'],
  ['Yang Feng',            62,  68,  38,  32,  40, 160, 195, 'changan',    'dongzhuo'],
  ['Han Xian',             58,  64,  30,  28,  35, 160, 195, 'changan',    'dongzhuo'],
  ['Duan Wei',             60,  62,  45,  50,  45, 158, 195, 'changan',    'dongzhuo'],
  ['Yang Qiu',             64,  70,  40,  36,  42, 165, 200, 'tianshui',   'mateng'],
  ['Cheng Yi',             60,  68,  36,  30,  40, 165, 200, 'tianshui',   'mateng'],
  ['Hou Xuan',             58,  66,  35,  32,  40, 168, 200, 'xiliang',    'mateng'],
  ['Li Kan',               56,  64,  34,  30,  40, 168, 200, 'xiliang',    'mateng'],
  ['Zhang Heng',           60,  66,  35,  30,  42, 166, 200, 'xiliang',    'mateng'],
  ['Liang Xing',           62,  70,  32,  28,  38, 167, 200, 'xiliang',    'mateng'],
  ['Yan Xing',             74,  88,  40,  30,  45, 170, 200, 'tianshui',   'mateng'],
  ['Yang Bai',             55,  60,  40,  44,  42, 165, 200, 'hanzhong',   'zhanglu'],
  ['Yang Ren',             62,  70,  38,  35,  40, 168, 200, 'hanzhong',   'zhanglu'],
  ['Gongsun Yue',          62,  66,  42,  40,  50, 165, 190, 'beiping',    'gongsunzan'],
  ['Guan Jing',            50,  40,  70,  72,  55, 165, 195, 'beiping',    'gongsunzan'],
  ['Zou Dan',              58,  64,  40,  38,  42, 160, 190, 'beiping',    'gongsunzan'],
  ['Guo Youzhi',           45,  30,  74,  82,  68, 185, 218, 'chengdu',    'liubei'],
  ['Zhang Xi',             66,  68,  50,  48,  48, 165, 195, 'jinyang',    null],
  ['Yang Bo',              64,  66,  40,  42,  45, 168, 198, 'hongnong',   null],
  ['Kou Feng',             60,  70,  38,  36,  44, 176, 205, 'xinye',      null],
  ['Chen Ying',            62,  64,  48,  50,  46, 172, 205, 'jiangxia',   null],
  ['Sun Guan',             64,  72,  38,  36,  44, 168, 196, 'langya',     null],
  ['Wu Dun',               62,  70,  36,  34,  40, 166, 196, 'langya',     null],
  ['Yin Li',               60,  68,  38,  40,  42, 167, 196, 'langya',     null],
  ['Zhang Bai',            58,  66,  34,  30,  40, 165, 194, 'runan',      null],
  ['Zhu Ling',             74,  76,  55,  52,  55, 165, 195, 'puyang',     null],
  ['Lu Kai',               56,  40,  78,  82,  66, 198, 220, 'wu',         null],
  ['Fan Jiang',            52,  66,  30,  28,  35, 178, 205, 'yongan',     null],
  ['Zhang Da',             50,  64,  30,  28,  32, 180, 205, 'yongan',     null],
  ['Shamoke',              70,  82,  30,  25,  45, 175, 210, 'wuling',     null],
  ['Ehe Shaoge',           64,  78,  28,  20,  40, 180, 220, 'jianning',   null],
  ['Yong Kai',             58,  62,  50,  45,  48, 175, 215, 'jianning',   null],
  ['Gao Ding',             60,  66,  40,  42,  45, 178, 215, 'jianning',   null],
  ['Zhu Bao',              56,  60,  42,  48,  44, 176, 215, 'jianning',   null],
  ['Wang Wei',             54,  40,  68,  74,  60, 175, 210, 'nanhai',     null],
  ['Shi Hui',              58,  56,  60,  66,  58, 168, 200, 'jiaozhi',    null],
  ['Bu Lu',                52,  58,  46,  50,  44, 172, 205, 'kuaiji',     null],
  ['Zhu Gai',              50,  54,  44,  52,  42, 174, 205, 'kuaiji',     null],
];

// Name pools for talents who rise from obscurity when the realm runs short of officers.
const SURNAMES = ['Wang', 'Li', 'Zhang', 'Liu', 'Chen', 'Yang', 'Zhao', 'Huang', 'Zhou', 'Wu', 'Xu', 'Sun', 'Hu', 'Zhu', 'Gao', 'Lin', 'He', 'Guo', 'Ma', 'Luo', 'Liang', 'Song', 'Zheng', 'Xie', 'Han', 'Tang', 'Feng', 'Yu', 'Dong', 'Xiao', 'Cheng', 'Cao', 'Yuan', 'Deng', 'Xu', 'Fu', 'Shen', 'Zeng', 'Peng', 'Lu', 'Su', 'Lu', 'Jiang', 'Cai', 'Jia', 'Ding', 'Wei', 'Xue', 'Ye', 'Yan', 'Yin', 'Fang', 'Shi', 'Pan', 'Du', 'Dai', 'Xia', 'Zhong', 'Wan', 'Tian', 'Ren', 'Jin', 'Fan', 'Kong', 'Gong', 'Hao', 'Bao', 'Meng', 'Qin', 'Qiu', 'Ruan', 'Tao', 'Wen', 'Yao', 'Zou'];
const GIVEN = ['Ping', 'Yi', 'Jun', 'Xian', 'Zhen', 'Kang', 'Feng', 'Yuan', 'Tai', 'Hong', 'Ji', 'Xin', 'Lie', 'Dan', 'Bao', 'Shao', 'Da', 'Zhi', 'Huan', 'Yong', 'Zhong', 'Hui', 'Meng', 'Xu', 'Fu', 'Sheng', 'Cheng', 'Rui', 'Heng', 'Wen', 'Bin', 'Ning', 'Qian', 'Jing', 'Shun', 'De', 'Zong', 'Gui', 'Long', 'Hu', 'Biao', 'Yao', 'Xun', 'Ang', 'Zhao', 'Ru', 'Mao', 'Chong', 'Dun', 'Shuang', 'Tong', 'Xiang', 'Zan', 'Fang', 'Gan', 'Qing', 'Wei', 'Liang', 'Ce', 'Quan', 'Ba', 'Jin', 'Kai', 'Yan', 'Yu', 'Xiu', 'Tan', 'Shang', 'Pi', 'Zhang', 'Ren', 'Yin', 'Lu', 'Xi', 'Bi'];

// Officer skills. Unlisted officers have none; generated talents may gain one.
// Outstations: buildings raised outside a city's walls on its hex battle map, unlocked by the ground there.
// hexes: terrain codes the site may stand on; near: hex distance from the city centre allowed; max: how many of the kind.
const SITE_TYPES = {
  mine:    { label: 'Mine',          glyph: '⛏', cost: 800, hexes: 'm',    near: [2, 6], max: 1, gold: 120, desc: 'Copper and iron from the hills: +120 gold a month, and the walls cost a fifth less to raise. Sacked for gold.' },
  village: { label: 'Village',       glyph: '⌂', cost: 400, hexes: 'a',    near: [2, 6], max: 3, food: 600, desc: 'A farming hamlet: +600 food a month (a quarter more in a granary province) and faster growth of the people. Sacked for grain, and the people suffer.' },
  pasture: { label: 'Horse pasture', glyph: '♞', cost: 600, hexes: 'p',    near: [2, 4], max: 1, desc: 'Studs and grazing: recruits arrive better trained, and in battle the holder\'s men charge harder on open ground. Sacked for horses, which go to the raider\'s home.' },
  lumber:  { label: 'Lumber camp',   glyph: '♣', cost: 400, hexes: 'f',    near: [2, 6], max: 1, desc: 'Timber: walls and ships cost three tenths less. In battle an attacker who holds it builds engines, and gates fall in two rams instead of three.' },
  docks:   { label: 'Docks',         glyph: '⚓', cost: 600, hexes: 'pafh', near: [2, 5], max: 1, gold: 80, water: true, desc: 'Wharves on the water: +80 gold a month and shipwrights work twice as fast. In battle the holder\'s ships land here without losing the day. Sacked: boats burn and the fleet suffers.' },
  salt:    { label: 'Salt pans',     glyph: '✶', cost: 700, hexes: 'pa',   near: [2, 6], max: 1, gold: 200, coast: true, desc: 'Salt from the sea: +200 gold a month, on top of the province\'s trade. A rich prize for a raider.' },
  tower:   { label: 'Watchtower',    glyph: '♜', cost: 500, hexes: 'h',    near: [2, 3], max: 1, desc: 'A beacon fort on a hill by the walls: spies and saboteurs are caught half the time. In battle it is a strong point (+25% defence) that gives its holder a place to shoot from and heartens him.' },
  market:  { label: 'Market town',   glyph: '⚖', cost: 500, hexes: 'pa',   near: [2, 3], max: 1, gold: 100, road: true, desc: 'A market on the road outside the gate: +100 gold a month. Sacked for gold, to the shame of the sacker.' },
};
const SITE_ORDER = ['mine', 'docks', 'village', 'salt', 'market', 'pasture', 'lumber', 'tower'];

const SKILL_INFO = {
  cavalry:   { label: 'Cavalry',   desc: 'Leads horsemen: +8% attack, +15% from horse country or over frozen rivers.' },
  naval:     { label: 'Naval',     desc: 'Master of ships: river and sea crossings cost half the losses and fight better.' },
  siege:     { label: 'Siege',     desc: 'Siegecraft: enemy walls count 30% less when this officer leads an attack.' },
  stratagem: { label: 'Stratagem', desc: 'Schemes come off 60% more often, attacking or defending.' },
  guardian:  { label: 'Guardian',  desc: 'Holds walls: +10% strength when defending.' },
  admin:     { label: 'Administrator', desc: 'Develops and pacifies half again as fast; doubles the governor bonus.' },
  orator:    { label: 'Orator',    desc: 'Persuades: +15% to recruit officers, +8% to envoy proposals, better pacification.' },
};
const OFFICER_SKILLS = {
  'Cao Cao': ['stratagem', 'admin'], 'Xiahou Dun': ['cavalry'], 'Xiahou Yuan': ['cavalry'], 'Cao Ren': ['guardian'], 'Xun Yu': ['admin', 'orator'], 'Yue Jin': ['siege'], 'Li Dian': ['guardian'],
  'Liu Bei': ['orator'], 'Guan Yu': ['cavalry', 'guardian'], 'Zhang Fei': ['cavalry'], 'Jian Yong': ['orator'], 'Sun Qian': ['orator'],
  'Sun Jian': ['cavalry'], 'Sun Ce': ['cavalry'], 'Huang Gai': ['naval'], 'Cheng Pu': ['naval', 'guardian'], 'Han Dang': ['naval'], 'Zhu Zhi': ['admin'],
  'Yuan Shao': ['admin'], 'Yan Liang': ['cavalry'], 'Wen Chou': ['cavalry'], 'Tian Feng': ['stratagem'], 'Ju Shou': ['stratagem', 'admin'], 'Zhang He': ['guardian', 'siege'],
  'Dong Zhuo': ['cavalry'], 'L\u00fc Bu': ['cavalry'], 'Li Ru': ['stratagem'], 'Zhang Liao': ['cavalry', 'guardian'], 'Xu Rong': ['siege'],
  'Ji Ling': ['siege'], 'Liu Biao': ['admin'], 'Huang Zhong': ['siege'], 'Cai Mao': ['naval'], 'Kuai Liang': ['admin'], 'Kuai Yue': ['stratagem'], 'Wen Ping': ['guardian'], 'Wei Yan': ['cavalry'],
  'Zhang Ren': ['guardian'], 'Yan Yan': ['guardian'], 'Huang Quan': ['admin'], 'Fa Zheng': ['stratagem'], 'Li Yan': ['admin'],
  'Ma Teng': ['cavalry'], 'Ma Chao': ['cavalry'], 'Pang De': ['cavalry'], 'Ma Dai': ['cavalry'], 'Han Sui': ['cavalry'],
  'Gongsun Zan': ['cavalry'], 'Zhao Yun': ['cavalry', 'guardian'], 'Tian Yu': ['admin'], 'Mi Zhu': ['admin', 'orator'], 'Chen Deng': ['stratagem'],
  'Kong Rong': ['orator'], 'Taishi Ci': ['cavalry'], 'Zhang Lu': ['orator'], 'Wang Lang': ['admin'], 'Yu Fan': ['orator'], 'Shi Xie': ['admin'],
  'Xu Huang': ['siege'], 'Zhou Yu': ['naval', 'stratagem'], 'Lu Su': ['orator', 'naval'], 'Xu Shu': ['stratagem'], 'Guo Jia': ['stratagem'], 'Xun You': ['stratagem'], 'Jia Xu': ['stratagem'],
  'Gan Ning': ['naval'], 'Zhang Zhao': ['admin', 'orator'], 'Dian Wei': ['guardian'], 'Xu Chu': ['guardian'], 'Chen Gong': ['stratagem'], 'Meng Huo': ['cavalry'], 'Zhang Song': ['orator'],
  'Zhuge Liang': ['stratagem', 'admin'], 'Sun Quan': ['orator', 'admin'], 'L\u00fc Meng': ['naval', 'stratagem'], 'Diaochan': ['orator'], 'Tadun': ['cavalry'], 'Kebineng': ['cavalry'], 'Zhang Yan': ['cavalry'],
  'Sima Yi': ['stratagem', 'siege'], 'Lu Xun': ['stratagem', 'naval'], 'Pang Tong': ['stratagem'], 'Jiang Wei': ['stratagem', 'cavalry'], 'Deng Ai': ['siege', 'stratagem'], 'Zhou Tai': ['guardian'],
  'Cao Pi': ['admin'], 'Cao Zhen': ['siege'], 'Cao Zhang': ['cavalry'], 'Guo Huai': ['guardian'], 'Hao Zhao': ['guardian'], 'Zhu Ran': ['naval'], 'Xu Sheng': ['naval'], 'Ding Feng': ['naval'],
  'Chen Qun': ['admin'], 'Man Chong': ['admin', 'guardian'], 'Yu Jin': ['guardian'], 'Ma Liang': ['orator'], 'Fei Yi': ['admin', 'orator'], 'Jiang Wan': ['admin'], 'Wang Ping': ['guardian'], 'Zhong Hui': ['stratagem'],
};

// Officer ties. Bonded officers (sworn brothers, close kin) stay loyal to each other, never defect, and will not serve a house
// while their brother rules another; enemies will not serve each other; rivals in one house grate on each other.
const OFFICER_TIES = {
  bonds: [
    ['Liu Bei', 'Guan Yu', 'Zhang Fei'],
    ['Cao Cao', 'Cao Ren', 'Cao Hong', 'Xiahou Dun', 'Xiahou Yuan', 'Cao Pi', 'Cao Zhang', 'Cao Zhi', 'Cao Zhen', 'Cao Xiu', 'Xiahou Shang'],
    ['Sun Jian', 'Sun Ce', 'Sun Quan'],
    ['Ma Teng', 'Ma Chao', 'Ma Dai'],
    ['Yuan Shao', 'Yuan Tan', 'Yuan Shang'],
    ['Sima Yi', 'Sima Shi', 'Sima Zhao'],
    ['Guan Yu', 'Guan Ping', 'Guan Xing'],
    ['Zhang Fei', 'Zhang Bao'],
    ['Meng Huo', 'Zhu Rong', 'Meng You'],
    ['Gongsun Du', 'Gongsun Kang'],
    ['Lu Kang', 'Lu Jun'],
    ['Shi Xie', 'Shi Yi'],
  ],
  enemies: [['Ma Chao', 'Cao Cao'], ['Zhang Fei', 'L\u00fc Bu'], ['Yuan Shao', 'Gongsun Zan'], ['Liu Bei', 'L\u00fc Bu'], ['Sun Ce', 'Huang Zhong']],
  rivals: [['Guo Tu', 'Tian Feng'], ['Guan Yu', 'Huang Zhong'], ['Li Jue', 'Guo Si'], ['Zhang Fei', 'Wei Yan'], ['Yan Liang', 'Zhang He'], ['Lu Su', 'Zhang Zhao']],
};

// Ruler titles, by tier. Each needs prestige and cities; the highest needs the Emperor or overwhelming power.
const TITLES = [
  { tier: 0, name: 'Lord',    prestige: 0,  cities: 0,  slots: 2 },
  { tier: 1, name: 'Marquis', prestige: 15, cities: 3,  slots: 4 },
  { tier: 2, name: 'Duke',    prestige: 35, cities: 8,  slots: 8 },
  { tier: 3, name: 'King',    prestige: 55, cities: 14, slots: 16 },
  { tier: 4, name: 'Emperor', prestige: 70, cities: 22, slots: 99 },
];
const RANKS = ['', 'Colonel', 'General', 'Marshal'];
const RANK_COST = [0, 300, 800, 2000];

// Treasures. `owner` is the officer who starts with it; `city` hides it in a city to be found by Search.
// types: weapon (WAR), horse (LDR, duels, and `escape` lets the rider avoid capture), book (INT/POL), seal (prestige).
const ITEMS = [
  { id: 'sky-piercer',   name: 'Sky Piercer Halberd',       type: 'weapon', bonus: { war: 5 },          owner: 'L\u00fc Bu',     desc: 'L\u00fc Bu\u2019s crescent halberd. WAR +5.' },
  { id: 'red-hare',      name: 'Red Hare',                  type: 'horse',  bonus: { ldr: 4 }, duel: 0.15, escape: true, owner: 'L\u00fc Bu', desc: 'The swiftest horse alive. LDR +4, duels +15%, and its rider is never taken when a city falls.' },
  { id: 'green-dragon',  name: 'Green Dragon Crescent Blade', type: 'weapon', bonus: { war: 5 },        owner: 'Guan Yu',     desc: 'Guan Yu\u2019s eighty-two-catty blade. WAR +5.' },
  { id: 'serpent-spear', name: 'Serpent Spear',             type: 'weapon', bonus: { war: 4 },          owner: 'Zhang Fei',   desc: 'Zhang Fei\u2019s eighteen-foot spear. WAR +4.' },
  { id: 'sword-of-trust', name: 'Sword of Trust',           type: 'weapon', bonus: { war: 2, chr: 3 },  owner: 'Cao Cao',     desc: 'Cao Cao\u2019s sword, Yitian. WAR +2, CHR +3.' },
  { id: 'shadow-runner', name: 'Shadow Runner',             type: 'horse',  bonus: { ldr: 3 }, duel: 0.05, escape: true, owner: 'Cao Cao', desc: 'Cao Cao\u2019s horse Jueying. LDR +3, and its rider escapes a falling city.' },
  { id: 'ingot-blade',   name: 'Ancient Ingot Blade',       type: 'weapon', bonus: { war: 3 },          owner: 'Sun Jian',    desc: 'The heirloom sword of the Sun. WAR +3.' },
  { id: 'imperial-seal', name: 'Imperial Seal',             type: 'seal',   bonus: {}, prestige: 10,    owner: null, city: null, desc: 'The Hereditary Seal of the Han. The holder\u2019s house gains 10 prestige while it is kept.' },
  { id: 'art-of-war',    name: 'The Art of War',            type: 'book',   bonus: { int: 5 },          owner: null, city: 'luoyang',   desc: 'Sunzi\u2019s treatise. INT +5.' },
  { id: 'taiping-manual', name: 'Taiping Manual',           type: 'book',   bonus: { int: 3, pol: 3 }, owner: null, city: 'ye',        desc: 'The Way of Great Peace, book of the Yellow Turbans. INT +3, POL +3.' },
  { id: 'hex-mark',      name: 'Hex Mark',                  type: 'horse',  bonus: { ldr: 3 }, duel: 0.05, escape: true, owner: null, city: 'xiangyang', desc: 'The horse Dilu, said to bring ill luck to its master. LDR +3, escapes a falling city.' },
  { id: 'sword-of-heaven', name: 'Sword of Heaven',         type: 'weapon', bonus: { war: 3 },          owner: null, city: 'changan',   desc: 'The blade Qinggang, which cuts iron like mud. WAR +3.' },
  { id: 'iron-bow',      name: 'Iron Bow',                  type: 'weapon', bonus: { war: 2, ldr: 2 },  owner: null, city: 'xiliang',   desc: 'A bow no ordinary man can draw. WAR +2, LDR +2.' },
  { id: 'spring-autumn', name: 'Spring and Autumn Annals',  type: 'book',   bonus: { pol: 4, chr: 2 },  owner: null, city: 'beihai',    desc: 'Confucius\u2019s chronicle. POL +4, CHR +2.' },
  { id: 'peacock-feather', name: 'Peacock Feather Cloak',   type: 'book',   bonus: { chr: 5 },          owner: null, city: 'chengdu',   desc: 'A cloak of a thousand feathers. CHR +5.' },
  { id: 'twin-swords',   name: 'Twin Swords',               type: 'weapon', bonus: { war: 3, chr: 2 },  owner: 'Liu Bei',     desc: 'Liu Bei\u2019s paired blades. WAR +3, CHR +2.' },
  { id: 'twin-halberds', name: 'Twin Halberds',             type: 'weapon', bonus: { war: 3 },          owner: 'Dian Wei',    desc: 'Dian Wei\u2019s eighty-catty halberds. WAR +3.' },
  { id: 'iron-scale',    name: 'Iron Scale Armour',         type: 'armor',  bonus: { ldr: 2 }, guard: true, owner: null, city: 'hongnong', desc: 'Armour no blade can pierce. LDR +2, and its wearer cannot be slain in a duel.' },
  { id: 'lacquer-armor', name: 'Black Lacquer Armour',      type: 'armor',  bonus: { ldr: 1, war: 1 }, guard: true, owner: null, city: 'jiangzhou', desc: 'Lacquered hide armour of the Ba tribes. LDR +1, WAR +1, and its wearer cannot be slain in a duel.' },
  { id: 'six-teachings', name: 'Six Secret Teachings',      type: 'book',   bonus: { ldr: 4 },          owner: null, city: 'hanzhong',  desc: 'The war manual of Jiang Ziya. LDR +4.' },
  { id: 'wuzi',          name: 'The Wuzi',                  type: 'book',   bonus: { ldr: 3, war: 2 },  owner: null, city: 'nanpi',     desc: 'Wu Qi\u2019s treatise on war. LDR +3, WAR +2.' },
  { id: 'analects',      name: 'The Analects',              type: 'book',   bonus: { pol: 3, chr: 3 },  owner: null, city: 'jinyang',   desc: 'The sayings of Confucius. POL +3, CHR +3.' },
  { id: 'shiji',         name: 'Records of the Grand Historian', type: 'book', bonus: { int: 2, pol: 3 }, owner: null, city: 'xiapi',   desc: 'Sima Qian\u2019s history of the world. INT +2, POL +3.' },
  { id: 'book-of-odes',  name: 'Book of Odes',              type: 'book',   bonus: { chr: 3, pol: 2 },  owner: null, city: 'runan',     desc: 'The ancient songs. CHR +3, POL +2.' },
  { id: 'yellow-dust',   name: 'Yellow Dust',               type: 'horse',  bonus: { ldr: 3 }, duel: 0.05, escape: true, owner: null, city: 'xiliang', desc: 'A steppe horse the colour of the Gobi. LDR +3, escapes a falling city.' },
  { id: 'flying-lightning', name: 'Flying Lightning',       type: 'horse',  bonus: { ldr: 3 }, duel: 0.08, escape: true, owner: null, city: 'zhongshan', desc: 'A Hebei racer. LDR +3, duels +8%, escapes a falling city.' },
  { id: 'gold-seal-shu', name: 'Gold Seal of Shu',          type: 'seal',   bonus: {}, prestige: 5,     owner: null, city: 'zitong',    desc: 'The seal of the ancient kings of Shu. The holder\u2019s house gains 5 prestige while it is kept.' },
  { id: 'edict',         name: 'Edict of Protection',       type: 'seal',   bonus: { chr: 2 }, prestige: 5, owner: null, city: null,    desc: 'The Emperor\u2019s own edict naming its holder protector of the Han. CHR +2 and 5 prestige while kept.' },
  { id: 'white-horse',   name: 'White Dragon',              type: 'horse',  bonus: { ldr: 3 }, duel: 0.05, escape: true, owner: 'Zhao Yun', desc: 'Zhao Yun\u2019s white stallion. LDR +3, escapes a falling city.' },
];

// Scripted historical deaths (optional). Fired on the given year/month if the
// officer is still alive. Causes are worded to stay plausible whatever the map looks like.
const HISTORICAL_DEATHS = [
  ['Hua Xiong',    191, 1,  'in battle at Sishui Pass, cut down by a champion of the coalition'],
  ['Sun Jian',     191, 4,  'in an ambush among the hills of Xiangyang, struck by arrows and falling stones'],
  ['Xu Rong',      192, 2,  'in battle against rebels in the west'],
  ['Liu Dai',      192, 4,  'in battle against the Yellow Turbans of Qing Province, having refused all counsel to stay behind his walls'],
  ['Dong Zhuo',    192, 4,  "at the palace gates, assassinated in Wang Yun's plot"],
  ['Li Ru',        192, 5,  'on the block after the fall of his master'],
  ['Tao Qian',     194, 12, 'of illness, worn out by the wars in Xu Province'],
  ['Zhang Chao',   195, 12, 'by his own hand as Cao Cao stormed Yongqiu, his whole family put to the sword'],
  ['Zang Hong',    196, 6,  'executed by Yuan Shao after holding Dongwuyang to the last grain for his dead lord'],
  ['Lu Kang',      195, 3,  'of illness after two years under siege, never having yielded'],
  ['Fan Chou',     195, 4,  'murdered at a banquet by a jealous rival'],
  ['Cao Bao',      196, 6,  'in a drunken quarrel that ended in bloodshed'],
  ['Dian Wei',     197, 1,  'holding a gate alone against a night attack, his body pierced by a dozen wounds'],
  ['Guo Si',       197, 8,  'stabbed by one of his own officers'],
  ['Liu Yao',      197, 10, 'of illness in the south'],
  ['Li Jue',       198, 4,  'hunted down and executed for his crimes in the capital'],
  ['Zhang Yang',   198, 11, 'murdered by a subordinate on the march'],
  ['Lü Bu',        198, 12, 'strangled at the White Gate Tower after his officers betrayed him'],
  ['Chen Gong',    198, 12, 'walking to the block with his head held high'],
  ['Gongsun Zan',  199, 3,  'by his own hand, in the flames of his besieged tower'],
  ['Yuan Shu',     199, 6,  'of despair on the road north, crying out for honeyed water'],
  ['Sun Ce',       200, 4,  'of wounds taken from assassins while hunting'],
  ['Yan Liang',    200, 4,  'in a single charge across the field at Baima, beheaded by a red-faced rider'],
  ['Wen Chou',     200, 5,  'in the rout at Yanjin, pursuing baggage instead of victory'],
  ['Tian Feng',    200, 10, 'in prison, executed by a lord who could not bear to face him after defeat'],
  ['Ju Shou',      200, 10, 'captured trying to return to his lord, and executed'],
  ['Liu Pi',       201, 9,  'in battle in Runan'],
  ['Yuan Shao',    202, 5,  'of a sickness that took him after his great defeat'],
  ['Ling Cao',     203, 8,  'in a river battle, felled by an arrow from a pirate turned general'],
  ['Gongsun Du',   204, 6,  'of illness in Liaodong'],
  ['Guo Tu',       205, 1,  'in the fall of Nanpi'],
  ['Yuan Tan',     205, 1,  'fleeing the fall of Nanpi'],
  ['Taishi Ci',    206, 12, 'of illness, lamenting that he had not yet won a great name'],
  ['Zhang Xiu',    207, 3,  'on campaign in the north'],
  ['Tadun',        207, 8,  'at White Wolf Mountain, cut down in a charge led by a general of the north'],
  ['Guo Jia',      207, 9,  'of fever on the northern campaign, at only thirty-seven'],
  ['Liu Biao',     208, 8,  'of illness in Xiangyang, as a great army marched south'],
  ['Kong Rong',    208, 8,  'executed for his sharp tongue, together with his household'],
  ['Chen Deng',    208, 10, 'of an illness caught from raw fish'],
  ['Zhou Yu',      210, 12, 'of illness at Baqiu, his plans for the west unfinished'],
  ['Cheng Pu',     210, 12, 'of illness soon after his friend and rival'],
  ['Ma Teng',      212, 5,  'executed at the capital together with his household'],
  ['Zhang Song',   212, 10, 'executed after his letters to a foreign lord were discovered'],
  ['Xun Yu',       212, 10, 'in silence, after receiving an empty food box from his lord'],
  ['Zhang Ren',    213, 6,  'refusing to surrender after capture, and executed'],
  ['Xun You',      214, 8,  'of illness on the southern campaign'],
  ['Kuai Yue',     214, 9,  'of illness'],
  ['Han Sui',      215, 5,  'of illness in the far west, aged over seventy'],
  ['Li Dian',      215, 7,  'of illness, aged only thirty-six'],
  ['Huang Gai',    215, 9,  'of illness, an old sea-dog to the end'],
  ['Sun Qian',     215, 11, 'of illness'],
  ['Zhang Lu',     216, 5,  'of illness after surrendering his mountain domain'],
  ['Lu Su',        217, 6,  'of illness, aged forty-five'],
  ['Yue Jin',      218, 11, 'of illness'],
  ['Xiahou Yuan',  219, 1,  'at Dingjun Mountain, cut down by an old general charging downhill'],
  ['Pang De',      219, 8,  'refusing to kneel after the floods drowned his army'],
  ['Liu Zhang',    219, 12, 'of illness in exile'],
  ['Guan Yu',      219, 12, 'captured at Maicheng and executed, unbowed'],
  ['Huang Zhong',  220, 8,  'of an arrow wound, an old man still first into battle'],
  ['Fa Zheng',     220, 4,  'of illness, deeply mourned by his lord'],
  ['Cao Cao',      220, 1,  'of a sickness of the head at Luoyang, leaving the realm to his sons'],
  ['Xiahou Dun',   220, 4,  'of illness'],
  ['Gan Ning',     220, 6,  'of illness'],
  ['Mi Zhu',       221, 3,  'of shame, after his brother betrayed his lord'],
  ['Zhang Fei',    221, 6,  'in his tent, murdered by two officers he had flogged'],
  ['Zhang Liao',   222, 9,  'of illness on his last campaign'],
  ['Ma Chao',      222, 12, 'of illness, aged forty-seven'],
  ['Cao Ren',      223, 3,  'of illness'],
  ['Liu Bei',      223, 4,  'of illness at Baidicheng, entrusting his son to his chancellor'],
  ['Jia Xu',       223, 6,  'of old age, the survivor of every court'],
  ['Zhu Zhi',      224, 3,  'of illness'],
  ['Han Dang',     226, 8,  'of illness'],
  ['Shi Xie',      226, 10, 'of old age, having ruled the far south for forty years'],
  ['Xu Huang',     227, 4,  'of illness'],
  ['Wang Lang',    228, 11, 'of illness'],
  ['Zhao Yun',     229, 7,  'of illness, undefeated to the last'],
  ['Zhang He',     231, 7,  'in an ambush at Wood Gate, shot through the knee'],
  ['Hua Xin',      232, 1,  'of old age'],
  ['Yu Fan',       233, 6,  'of old age in exile'],
  ['Wei Yan',      234, 10, 'killed by his own comrades after his general died on campaign'],
  ['Li Yan',       234, 11, 'of grief on hearing that his general had died'],
  ['Kebineng',     235, 6,  'in his own tent, stabbed by a swordsman sent from the frontier'],
  ['Pang Tong',    214, 7,  'struck by an arrow at the Fallen Phoenix Slope during the march on Chengdu'],
  ['Ma Liang',     222, 8,  'in the rout after the great defeat on the Yangtze'],
  ['Cao Pi',       226, 6,  'of illness, aged forty'],
  ['Cao Zhen',     231, 4,  'of illness after the failed campaign against Shu'],
  ['Ma Su',        228, 5,  'executed after losing Jieting, his commander weeping as he signed the order'],
  ['Zhu Ran',      249, 3,  'of illness'],
  ['Lu Xun',       245, 2,  'of grief and anger over the quarrel of the princes'],
  ['Sima Yi',      251, 8,  'of old age, master of the Wei court'],
  ['Zhang Zhao',   236, 3,  'of old age, aged eighty'],
  ['Wu Yi',        237, 5,  'of illness'],
  ['Huang Quan',   240, 4,  'of illness'],
];

// ------------------------------------------------------------------
//  Scenarios. Each names its year, which houses are alive with which ruler and cities, the officers of each house
//  (any officer of the base roster, a later arrival whose year has come, or a `create` entry), who holds the Emperor,
//  and starting treaties. Officers not placed are free if alive at that date and dead if their scripted year has passed.
//  Houses not listed are dead. A house may be `dynamic` (founded in play, e.g. L\u00fc Bu) with its own colour.
// ------------------------------------------------------------------
// Officers that exist only through scenarios: [name, LDR, WAR, INT, POL, CHR, born]
const SCENARIO_CREATED = [
  ['Sun Quan', 82, 70, 78, 85, 90, 182], ['Zhuge Liang', 88, 55, 100, 98, 92, 181], ['Yuan Shang', 68, 72, 55, 52, 62, 176],
  ['Liu Shan', 40, 30, 45, 55, 60, 207], ['Liu Qi', 50, 40, 55, 62, 60, 190], ['Cheng Yu', 72, 60, 90, 82, 60, 141], ['Hou Cheng', 58, 66, 38, 30, 35, 160], ['Song Xian', 55, 64, 32, 28, 30, 162], ['Wei Xu', 54, 65, 30, 26, 30, 163], ['Diaochan', 20, 10, 70, 60, 100, 175], ['L\u00fc Meng', 84, 86, 72, 60, 66, 178],
];
const SCENARIOS = [
  { id: '190', title: 'The Coalition Against Dong Zhuo', year: 190, month: 1, base: true,
    intro: 'Dong Zhuo has seized the capital and holds the child Emperor hostage. Warlords across the land raise their banners, each dreaming of restoring the Han... or replacing it. Unite the realm under your rule.' },
  { id: '194', title: 'Cao Cao and L\u00fc Bu', year: 194, month: 6,
    intro: 'Dong Zhuo is dead and his generals brawl over Chang\u2019an. L\u00fc Bu has seized Yan Province behind Cao Cao\u2019s back, Tao Qian lies dying in Xu, and the Sun family, their father slain, serve Yuan Shu while dreaming of the Yangtze.',
    emperor: 'dongzhuo',
    houses: {
      caocao:    { ruler: 'Cao Cao', cities: ['chenliu', 'xuchang'], officers: ['Cao Cao', 'Xiahou Dun', 'Xiahou Yuan', 'Cao Ren', 'Cao Hong', 'Xun Yu', 'Yue Jin', 'Li Dian', 'Dian Wei', 'Yu Jin', 'Man Chong', 'Guo Jia', 'Xun You', 'Cheng Yu*'] },
      lubu:      { ruler: 'L\u00fc Bu', name: 'L\u00fc Bu', color: '#b22222', wanderer: true, persona: ['treacherous', 'reckless'], aggr: 1.5, cities: ['puyang'], officers: ['L\u00fc Bu', 'Zhang Liao', 'Chen Gong', 'Hou Cheng*', 'Song Xian*', 'Wei Xu*', 'Diaochan*'] },
      liubei:    { ruler: 'Liu Bei', cities: ['xiaopei'], officers: ['Liu Bei', 'Guan Yu', 'Zhang Fei', 'Jian Yong', 'Sun Qian', 'Zhao Yun'] },
      zhangchao: { ruler: 'Zhang Chao', cities: ['guangling'], officers: ['Zhang Chao', 'Zang Hong'] },
      taoqian:   { ruler: 'Tao Qian', cities: ['xiapi', 'langya', 'pengcheng'], officers: ['Tao Qian', 'Cao Bao', 'Mi Zhu', 'Chen Deng', 'Zang Ba'] },
      yuanshao:  { ruler: 'Yuan Shao', cities: ['ye', 'nanpi', 'zhongshan', 'pingyuan', 'jinyang', 'shangdang'], officers: ['Yuan Shao', 'Yan Liang', 'Wen Chou', 'Tian Feng', 'Ju Shou', 'Guo Tu', 'Zhang He', 'Gao Lan', 'Yuan Tan'] },
      gongsunzan: { ruler: 'Gongsun Zan', cities: ['beiping'], officers: ['Gongsun Zan', 'Yan Gang', 'Tian Yu'] },
      gongsundu: { ruler: 'Gongsun Du', cities: ['xiangping'], officers: ['Gongsun Du', 'Gongsun Kang'] },
      kongrong:  { ruler: 'Kong Rong', cities: ['beihai', 'donglai'], officers: ['Kong Rong', 'Taishi Ci', 'Wang Xiu'] },
      dongzhuo:  { ruler: 'Li Jue', name: 'Li Jue', cities: ['changan', 'hongnong', 'luoyang', 'hedong'], officers: ['Li Jue', 'Guo Si', 'Fan Chou', 'Jia Xu', 'Zhong Yao'] },
      mateng:    { ruler: 'Ma Teng', cities: ['xiliang', 'tianshui', 'longxi'], officers: ['Ma Teng', 'Ma Chao', 'Pang De', 'Ma Dai', 'Han Sui'] },
      zhanglu:   { ruler: 'Zhang Lu', cities: ['hanzhong'], officers: ['Zhang Lu', 'Yang Ang', 'Yan Pu'] },
      liuzhang:  { ruler: 'Liu Zhang', cities: ['chengdu', 'jiangzhou', 'zitong', 'yongan', 'zangke'], officers: ['Liu Zhang', 'Zhang Ren', 'Yan Yan', 'Huang Quan', 'Fa Zheng', 'Li Yan', 'Wu Yi', 'Zhao Wei', 'Zhang Song'] },
      yuanshu:   { ruler: 'Yuan Shu', cities: ['shouchun', 'runan', 'lujiang'], officers: ['Yuan Shu', 'Ji Ling', 'Zhang Xun', 'Yang Hong', 'Yan Xiang'] },
      sunjian:   { ruler: 'Sun Ce', name: 'Sun Ce', guestOf: 'yuanshu', officers: ['Sun Ce', 'Huang Gai', 'Cheng Pu', 'Han Dang', 'Zhu Zhi', 'Zhou Tai', 'Jiang Qin'] },
      liubiao:   { ruler: 'Liu Biao', cities: ['xiangyang', 'jiangxia', 'jiangling', 'xinye', 'wan', 'changsha', 'wuling', 'guiyang', 'lingling'], officers: ['Liu Biao', 'Huang Zhong', 'Cai Mao', 'Kuai Liang', 'Kuai Yue', 'Wen Ping', 'Wei Yan', 'Zhang Xiu'] },
      liuyao:    { ruler: 'Liu Yao', cities: ['wu', 'jianye', 'chaisang', 'danyang'], officers: ['Liu Yao', 'Zhang Ying', 'Fan Neng', 'Taishi Ci?'] },
      wanglang:  { ruler: 'Wang Lang', cities: ['kuaiji'], officers: ['Wang Lang', 'Yu Fan', 'Zhou Xin', 'Hua Xin'] },
      shixie:    { ruler: 'Shi Xie', cities: ['jiaozhi', 'nanhai', 'hepu'], officers: ['Shi Xie', 'Shi Yi'] },
      menghuo:   { ruler: 'Meng Huo', cities: ['jianning'], officers: ['Meng Huo', 'Zhu Rong', 'Meng You'] },
      wuhuan:    { ruler: 'Tadun', cities: ['liucheng'], officers: ['Tadun', 'Louban', 'Supuyan'] },
      xianbei:   { ruler: 'Kebineng', cities: ['danhan'], officers: ['Kebineng', 'Budugen', 'Fuluohan'] },
    },
    treaties: [],
  },
  { id: '200', title: 'Guandu', year: 200, month: 1,
    intro: 'Cao Cao holds the Emperor at Xuchang and has crushed L\u00fc Bu and Yuan Shu. North of the Yellow River, Yuan Shao commands the greatest host in the land and marches south. Sun Quan, barely twenty, has just inherited Jiangdong; Liu Bei, driven from Xu once more, shelters with Yuan Shao.',
    emperor: 'caocao',
    houses: {
      caocao:    { ruler: 'Cao Cao', title: 2, garrison: 0.8, training: 75, cities: ['xuchang', 'chenliu', 'puyang', 'xiaopei', 'xiapi', 'langya', 'runan', 'luoyang', 'hongnong', 'wan', 'shouchun', 'pengcheng', 'hedong', 'guangling'], officers: ['Cao Cao', 'Xiahou Dun', 'Xiahou Yuan', 'Cao Ren', 'Cao Hong', 'Xun Yu', 'Yue Jin', 'Li Dian', 'Yu Jin', 'Man Chong', 'Guo Jia', 'Xun You', 'Jia Xu', 'Zhang Liao', 'Xu Huang', 'Xu Chu', 'Zang Ba', 'Chen Qun', 'Zhong Yao', 'Zhang Xiu', 'Guan Yu'] },
      yuanshao:  { ruler: 'Yuan Shao', title: 2, garrison: 1.4, cities: ['ye', 'nanpi', 'zhongshan', 'pingyuan', 'jinyang', 'beiping', 'beihai', 'shangdang', 'donglai'], officers: ['Yuan Shao', 'Yan Liang', 'Wen Chou', 'Tian Feng', 'Ju Shou', 'Guo Tu', 'Zhang He', 'Gao Lan', 'Yuan Tan', 'Yuan Shang', 'Tian Yu'] },
      liubei:    { ruler: 'Liu Bei', guestOf: 'yuanshao', officers: ['Liu Bei', 'Zhang Fei', 'Jian Yong', 'Sun Qian', 'Zhao Yun', 'Mi Zhu', 'Chen Dao'] },
      sunjian:   { ruler: 'Sun Quan', name: 'Sun Quan', title: 1, cities: ['jianye', 'wu', 'kuaiji', 'chaisang', 'lujiang', 'yuzhang', 'danyang', 'jianan'], officers: ['Sun Quan', 'Zhou Yu', 'Lu Su', 'Zhang Zhao', 'Huang Gai', 'Cheng Pu', 'Han Dang', 'Zhu Zhi', 'Zhou Tai', 'Jiang Qin', 'Chen Wu', 'Dong Xi', 'Zhuge Jin', 'Bu Zhi', 'Gu Yong', 'Pan Zhang', 'Xu Sheng', 'L\u00fc Meng*', 'Taishi Ci'] },
      liubiao:   { ruler: 'Liu Biao', title: 1, cities: ['xiangyang', 'jiangxia', 'jiangling', 'xinye', 'changsha', 'wuling', 'guiyang', 'lingling'], officers: ['Liu Biao', 'Huang Zhong', 'Cai Mao', 'Kuai Liang', 'Kuai Yue', 'Wen Ping', 'Wei Yan', 'Liao Hua'] },
      liuzhang:  { ruler: 'Liu Zhang', cities: ['chengdu', 'jiangzhou', 'zitong', 'yongan', 'zangke'], officers: ['Liu Zhang', 'Zhang Ren', 'Yan Yan', 'Huang Quan', 'Fa Zheng', 'Li Yan', 'Wu Yi', 'Zhao Wei', 'Zhang Song'] },
      zhanglu:   { ruler: 'Zhang Lu', cities: ['hanzhong'], officers: ['Zhang Lu', 'Yang Ang', 'Yan Pu'] },
      mateng:    { ruler: 'Ma Teng', cities: ['xiliang', 'tianshui', 'changan', 'longxi', 'wudu'], officers: ['Ma Teng', 'Ma Chao', 'Pang De', 'Ma Dai', 'Han Sui'] },
      gongsundu: { ruler: 'Gongsun Du', cities: ['xiangping'], officers: ['Gongsun Du', 'Gongsun Kang'] },
      shixie:    { ruler: 'Shi Xie', cities: ['jiaozhi', 'nanhai', 'hepu'], officers: ['Shi Xie', 'Shi Yi'] },
      menghuo:   { ruler: 'Meng Huo', cities: ['jianning'], officers: ['Meng Huo', 'Zhu Rong', 'Meng You'] },
      zhangyan:  { ruler: 'Zhang Yan', cities: [], officers: [] },
      wuhuan:    { ruler: 'Tadun', cities: ['liucheng'], officers: ['Tadun', 'Louban', 'Supuyan'] },
      xianbei:   { ruler: 'Kebineng', cities: ['danhan'], officers: ['Kebineng', 'Budugen', 'Fuluohan'] },
    },
    treaties: [['sunjian', 'liubiao', 'ceasefire'], ['wuhuan', 'yuanshao', 'alliance']],
    relations: [['caocao', 'yuanshao', -60], ['liubei', 'caocao', -50], ['sunjian', 'liubiao', -40]],
  },
  { id: '208', title: 'Red Cliffs', year: 208, month: 7,
    intro: 'Cao Cao has crushed the Yuans, taken Hebei, and now sweeps south into a leaderless Jing Province. Liu Bei, with Zhuge Liang newly at his side, flees toward the river. Only Sun Quan\u2019s fleets stand between Cao Cao and the whole of China.',
    emperor: 'caocao',
    houses: {
      caocao:    { ruler: 'Cao Cao', title: 2, garrison: 0.85, cities: ['xuchang', 'chenliu', 'puyang', 'xiaopei', 'xiapi', 'langya', 'runan', 'luoyang', 'hongnong', 'wan', 'shouchun', 'ye', 'nanpi', 'zhongshan', 'pingyuan', 'jinyang', 'beiping', 'beihai', 'xinye', 'xiangyang', 'changan', 'pengcheng', 'hedong', 'shangdang', 'guangling', 'donglai'], officers: ['Cao Cao', 'Xiahou Dun', 'Xiahou Yuan', 'Cao Ren', 'Cao Hong', 'Xun Yu', 'Yue Jin', 'Li Dian', 'Yu Jin', 'Man Chong', 'Xun You', 'Jia Xu', 'Zhang Liao', 'Xu Huang', 'Xu Chu', 'Zang Ba', 'Chen Qun', 'Zhong Yao', 'Zhang He', 'Gao Lan', 'Cao Pi', 'Cao Zhen', 'Cao Xiu', 'Cao Zhang', 'Sima Yi', 'Jia Kui', 'Cai Mao', 'Kuai Yue', 'Wen Ping', 'Zhang Yang?'] },
      liubei:    { ruler: 'Liu Bei', title: 1, garrison: 1.5, fleet: 50, cities: ['jiangxia'], officers: ['Liu Bei', 'Guan Yu', 'Zhang Fei', 'Zhao Yun', 'Zhuge Liang', 'Jian Yong', 'Sun Qian', 'Mi Zhu', 'Chen Dao', 'Ma Liang', 'Guan Ping', 'Liu Feng', 'Huo Jun', 'Liao Hua'] },
      sunjian:   { ruler: 'Sun Quan', name: 'Sun Quan', title: 2, fleet: 85, garrison: 1.2, cities: ['jianye', 'wu', 'kuaiji', 'chaisang', 'lujiang', 'yuzhang', 'danyang', 'jianan'], officers: ['Sun Quan', 'Zhou Yu', 'Lu Su', 'Zhang Zhao', 'Huang Gai', 'Cheng Pu', 'Han Dang', 'Zhu Zhi', 'Zhou Tai', 'Jiang Qin', 'Chen Wu', 'Dong Xi', 'Zhuge Jin', 'Bu Zhi', 'Gu Yong', 'Pan Zhang', 'Xu Sheng', 'Zhu Ran', 'Lu Xun', 'Zhu Huan', 'Ling Tong', 'Gan Ning', 'L\u00fc Meng*', 'Taishi Ci?'] },
      liuzhang:  { ruler: 'Liu Zhang', cities: ['chengdu', 'jiangzhou', 'zitong', 'yongan', 'zangke'], officers: ['Liu Zhang', 'Zhang Ren', 'Yan Yan', 'Huang Quan', 'Fa Zheng', 'Li Yan', 'Wu Yi', 'Zhao Wei', 'Zhang Song'] },
      zhanglu:   { ruler: 'Zhang Lu', cities: ['hanzhong', 'shangyong'], officers: ['Zhang Lu', 'Yang Ang', 'Yan Pu', 'Pang De'] },
      mateng:    { ruler: 'Ma Teng', cities: ['xiliang', 'tianshui', 'longxi', 'wudu'], officers: ['Ma Teng', 'Ma Chao', 'Ma Dai', 'Han Sui'] },
      gongsundu: { ruler: 'Gongsun Kang', name: 'Gongsun Kang', cities: ['xiangping'], officers: ['Gongsun Kang'] },
      shixie:    { ruler: 'Shi Xie', cities: ['jiaozhi', 'nanhai', 'hepu'], officers: ['Shi Xie', 'Shi Yi'] },
      menghuo:   { ruler: 'Meng Huo', cities: ['jianning'], officers: ['Meng Huo', 'Zhu Rong', 'Meng You'] },
      liubiao:   { ruler: 'Liu Qi*', name: 'Liu Qi', cities: ['jiangling', 'changsha', 'wuling', 'guiyang', 'lingling'], officers: ['Liu Qi*', 'Huang Zhong', 'Kuai Liang', 'Wei Yan', 'Zhao Lei'] },
      xianbei:   { ruler: 'Kebineng', cities: ['danhan'], officers: ['Kebineng', 'Budugen', 'Fuluohan'] },
    },
    treaties: [['liubei', 'sunjian', 'alliance']],
    relations: [['caocao', 'liubei', -80], ['caocao', 'sunjian', -50], ['liubei', 'sunjian', 40]],
  },
  { id: '219', title: 'Hanzhong and Fancheng', year: 219, month: 7,
    intro: 'Liu Bei has taken Shu and Hanzhong and been proclaimed King of Hanzhong; Guan Yu drives north from Jiangling toward Xuchang. Cao Cao, old and ill, holds the north. Sun Quan watches the Yangtze with L\u00fc Meng and Lu Xun, and his patience with his ally is wearing thin.',
    emperor: 'caocao',
    houses: {
      caocao:    { ruler: 'Cao Cao', title: 3, garrison: 1.0, cities: ['xuchang', 'chenliu', 'puyang', 'xiaopei', 'xiapi', 'langya', 'runan', 'luoyang', 'hongnong', 'wan', 'shouchun', 'ye', 'nanpi', 'zhongshan', 'pingyuan', 'jinyang', 'beiping', 'beihai', 'xinye', 'xiangyang', 'changan', 'tianshui', 'xiliang', 'liucheng', 'xiangping', 'pengcheng', 'hedong', 'shangdang', 'guangling', 'longxi', 'wudu', 'donglai'], officers: ['Cao Cao', 'Cao Ren', 'Cao Hong', 'Yue Jin', 'Yu Jin', 'Man Chong', 'Jia Xu', 'Zhang Liao', 'Xu Huang', 'Xu Chu', 'Zang Ba', 'Chen Qun', 'Zhong Yao', 'Zhang He', 'Cao Pi', 'Cao Zhen', 'Cao Xiu', 'Cao Zhang', 'Cao Zhi', 'Sima Yi', 'Jia Kui', 'Guo Huai', 'Hao Zhao', 'Xiahou Shang', 'Wang Shuang', 'Pang De', 'Wen Ping', 'Cai Mao', 'Kuai Yue', 'Han Sui'] },
      liubei:    { ruler: 'Liu Bei', title: 3, garrison: 1.0, walls: 250, training: 75, cities: ['chengdu', 'jiangzhou', 'zitong', 'yongan', 'hanzhong', 'shangyong', 'jiangling', 'wuling', 'guiyang', 'changsha', 'lingling', 'zangke'], officers: ['Liu Bei', 'Guan Yu', 'Zhang Fei', 'Zhao Yun', 'Zhuge Liang', 'Ma Chao', 'Ma Dai', 'Huang Zhong', 'Wei Yan', 'Fa Zheng', 'Huang Quan', 'Li Yan', 'Wu Yi', 'Jian Yong', 'Sun Qian', 'Mi Zhu', 'Chen Dao', 'Ma Liang', 'Ma Su', 'Guan Ping', 'Liu Feng', 'Huo Jun', 'Liao Hua', 'Jiang Wan', 'Fei Yi', 'Wu Ban', 'Zhang Yi', 'Ma Zhong', 'Wang Ping', 'Zhang Ni', 'Guan Xing', 'Zhang Bao', 'Zhao Lei', 'Yan Yan'] },
      sunjian:   { ruler: 'Sun Quan', name: 'Sun Quan', title: 2, garrison: 1.0, fleet: 85, walls: 100, cities: ['jianye', 'wu', 'kuaiji', 'chaisang', 'lujiang', 'yuzhang', 'jiangxia', 'danyang', 'jianan'], officers: ['Sun Quan', 'Lu Su', 'Zhang Zhao', 'Han Dang', 'Zhu Zhi', 'Zhou Tai', 'Jiang Qin', 'Zhuge Jin', 'Bu Zhi', 'Gu Yong', 'Pan Zhang', 'Xu Sheng', 'Zhu Ran', 'Lu Xun', 'Zhu Huan', 'Ling Tong', 'Gan Ning', 'L\u00fc Meng*', 'Quan Cong', 'Ding Feng'] },
      shixie:    { ruler: 'Shi Xie', cities: ['jiaozhi', 'nanhai', 'hepu'], officers: ['Shi Xie', 'Shi Yi'] },
      menghuo:   { ruler: 'Meng Huo', cities: ['jianning'], officers: ['Meng Huo', 'Zhu Rong', 'Meng You'] },
      xianbei:   { ruler: 'Kebineng', cities: ['danhan'], officers: ['Kebineng', 'Budugen', 'Fuluohan'] },
    },
    treaties: [['liubei', 'sunjian', 'ceasefire']],
    relations: [['caocao', 'liubei', -80], ['caocao', 'sunjian', -20], ['liubei', 'sunjian', -10]],
  },
  { id: '225', title: 'The Three Kingdoms', year: 225, month: 1,
    intro: 'Cao Cao, Liu Bei and Guan Yu are dead. Cao Pi has deposed the last Han emperor and reigns as Emperor of Wei; Liu Shan sits on the throne of Shu with Zhuge Liang governing in his name; Sun Quan rules Wu from Jianye. Three kingdoms, one empire, and the war that will decide it.',
    emperor: null,
    houses: {
      caocao:    { ruler: 'Cao Pi', name: 'Cao Pi', title: 4, garrison: 1.0, cities: ['xuchang', 'chenliu', 'puyang', 'xiaopei', 'xiapi', 'langya', 'runan', 'luoyang', 'hongnong', 'wan', 'shouchun', 'ye', 'nanpi', 'zhongshan', 'pingyuan', 'jinyang', 'beiping', 'beihai', 'xinye', 'xiangyang', 'changan', 'tianshui', 'xiliang', 'liucheng', 'xiangping', 'shangyong', 'pengcheng', 'hedong', 'shangdang', 'guangling', 'longxi', 'wudu', 'donglai'], officers: ['Cao Pi', 'Cao Zhen', 'Cao Xiu', 'Cao Zhi', 'Sima Yi', 'Zhang He', 'Xu Huang', 'Man Chong', 'Chen Qun', 'Jia Kui', 'Guo Huai', 'Hao Zhao', 'Xiahou Shang', 'Wang Shuang', 'Zang Ba', 'Wen Ping', 'Deng Ai', 'Zhu Ju?'] },
      liubei:    { ruler: 'Liu Shan*', name: 'Liu Shan', title: 4, garrison: 1.1, walls: 300, training: 80, cities: ['chengdu', 'jiangzhou', 'zitong', 'yongan', 'hanzhong', 'jianning', 'zangke'], officers: ['Liu Shan*', 'Zhuge Liang', 'Zhao Yun', 'Wei Yan', 'Ma Dai', 'Li Yan', 'Wu Yi', 'Ma Su', 'Jiang Wan', 'Fei Yi', 'Wu Ban', 'Zhang Yi', 'Ma Zhong', 'Wang Ping', 'Zhang Ni', 'Guan Xing', 'Zhang Bao', 'Liao Hua', 'Jiang Wei', 'Zhang Yi (Shu)'] },
      sunjian:   { ruler: 'Sun Quan', name: 'Sun Quan', title: 3, garrison: 1.0, fleet: 90, walls: 150, cities: ['jianye', 'wu', 'kuaiji', 'chaisang', 'lujiang', 'yuzhang', 'jiangxia', 'jiangling', 'wuling', 'guiyang', 'changsha', 'nanhai', 'jiaozhi', 'danyang', 'lingling', 'hepu', 'jianan'], officers: ['Sun Quan', 'Zhang Zhao', 'Han Dang', 'Zhou Tai', 'Zhuge Jin', 'Bu Zhi', 'Gu Yong', 'Pan Zhang', 'Xu Sheng', 'Zhu Ran', 'Lu Xun', 'Zhu Huan', 'Quan Cong', 'Ding Feng', 'Zhu Ju', 'Zhuge Ke'] },
      menghuo:   { ruler: 'Meng Huo', cities: [], officers: ['Meng Huo', 'Zhu Rong', 'Meng You'], guestOf: null, dead: true },
      xianbei:   { ruler: 'Kebineng', cities: ['danhan'], officers: ['Kebineng', 'Budugen', 'Fuluohan'] },
    },
    treaties: [['liubei', 'sunjian', 'alliance']],
    relations: [['caocao', 'liubei', -70], ['caocao', 'sunjian', -50], ['liubei', 'sunjian', 30]],
    created: [
      ['Liu Shan', 40, 30, 45, 55, 60, 207], ['Liu Qi', 50, 40, 55, 62, 60, 190], ['Cheng Yu', 72, 60, 90, 82, 60, 141], ['Hou Cheng', 58, 66, 38, 30, 35, 160], ['Song Xian', 55, 64, 32, 28, 30, 162], ['Wei Xu', 54, 65, 30, 26, 30, 163], ['Diaochan', 20, 10, 70, 60, 100, 175], ['L\u00fc Meng', 84, 86, 72, 60, 66, 178],
    ],
  },
];

// ------------------------------------------------------------------
//  Encyclopaedia: short biographies, city notes and the meaning of events.
// ------------------------------------------------------------------
const BIOS = {
  'Cao Cao': 'Poet, general and statesman; the most gifted man of his age and the most ruthless. From a single county he built the state of Wei that his son would make an empire.',
  'Liu Bei': 'A sandal-maker of imperial descent whose charisma bound Guan Yu, Zhang Fei and Zhuge Liang to him through decades of defeat, until he was proclaimed Emperor of Shu-Han in Chengdu.',
  'Sun Jian': 'The Tiger of Jiangdong, boldest general of the coalition against Dong Zhuo. Died in an ambush in 191, leaving his sons a name and an army.',
  'Sun Ce': 'The Little Conqueror. In five years he carved a realm out of Jiangdong with a borrowed army, and died at twenty-five from an assassin\u2019s wound.',
  'Sun Quan': 'Ruled Wu for fifty years, from the fires of Red Cliffs to a bitter old age. A judge of men who let his generals win his battles.',
  'Yuan Shao': 'Head of the empire\u2019s grandest family and lord of the north. Slow to decide and quick to resent advice; lost everything at Guandu.',
  'Dong Zhuo': 'The frontier general who seized the capital, deposed one emperor, burned Luoyang and died at the hands of his own champion.',
  'L\u00fc Bu': 'The finest warrior of the age and the least faithful. Killed two lords who trusted him, wandered from court to court, and was strangled at the White Gate.',
  'Zhuge Liang': 'The Sleeping Dragon. Strategist, administrator, inventor and chancellor of Shu; five times he marched north against Wei and five times returned.',
  'Guan Yu': 'Liu Bei\u2019s sworn brother, later worshipped as the god of war. Unmatched in battle, undone by pride at Fancheng.',
  'Zhang Fei': 'Liu Bei\u2019s other sworn brother: a bellowing giant on the bridge at Changban, a drunkard in camp, murdered by men he had flogged.',
  'Zhao Yun': 'The gentleman general of Shu, who carried Liu Bei\u2019s infant son through Cao Cao\u2019s whole army at Changban and never lost a battle.',
  'Zhou Yu': 'Sun Ce\u2019s friend and Sun Quan\u2019s admiral; the architect of victory at Red Cliffs, dead at thirty-five with his plans for the west unfinished.',
  'Sima Yi': 'Cao Cao distrusted him and Cao Pi relied on him. Patient, unreadable, the man who outlasted Zhuge Liang and whose grandson founded the Jin.',
  'Lu Xun': 'A scholar who became Wu\u2019s greatest commander: he burned Liu Bei\u2019s camps at Yiling and held the Yangtze for a generation.',
  'Xun Yu': 'Cao Cao\u2019s chief minister, a Confucian who served a warlord in the hope of restoring the Han, and died when he saw the hope was false.',
  'Guo Jia': 'Cao Cao\u2019s favourite strategist, dead at thirty-seven. "Had Guo Jia lived," Cao Cao said after Red Cliffs, "I would not have come to this."',
  'Jia Xu': 'The survivor: adviser to Dong Zhuo\u2019s generals, to Zhang Xiu and to Cao Cao, each time landing on his feet. Died in his bed at seventy-seven.',
  'Ma Chao': 'Ma Teng\u2019s son, the Splendid, a cavalry general of terrifying prowess whose family Cao Cao slaughtered and who ended his days serving Shu.',
  'Huang Zhong': 'A veteran already grey when history noticed him, who cut down Xiahou Yuan at Dingjun Mountain in his seventies.',
  'Dian Wei': 'Cao Cao\u2019s bodyguard, a giant who wielded twin halberds and died holding a camp gate alone against Zhang Xiu\u2019s night attack.',
  'Xu Chu': 'The Tiger Fool, who once dragged an ox backwards and guarded Cao Cao for thirty years without a thought for himself.',
  'Zhang Liao': 'L\u00fc Bu\u2019s loyal lieutenant, spared at the White Gate; as Cao Cao\u2019s general he broke Sun Quan\u2019s army at Hefei with eight hundred men.',
  'Pang Tong': 'The Fledgling Phoenix, Zhuge Liang\u2019s equal in reputation, killed by an arrow on the road to Chengdu before he could prove it.',
  'Lu Su': 'The generous strategist who brought Sun Quan and Liu Bei together against Cao Cao, and kept the alliance alive while they quarrelled over Jing.',
  'L\u00fc Meng': 'A ruffian who taught himself letters, took Jiangling from under Guan Yu\u2019s nose and died within the year.',
  'Tao Qian': 'The elderly governor of Xu who bequeathed his province to Liu Bei, the only lord ever to give Liu Bei anything freely.',
  'Zhang Chao': 'Administrator of Guangling and younger brother of Zhang Miao of Chenliu; a founder of the coalition against Dong Zhuo who later sided with L\u00fc Bu against Cao Cao and died at Yongqiu.',
  'Zang Hong': 'Zhang Chao\u2019s lieutenant and the most stubborn loyalist of the age: he held Dongwuyang for Yuan Shao, then defied him when Yuan Shao let Zhang Chao die, and was executed after a year-long siege.',
  'Kong Rong': 'Descendant of Confucius, scholar and wit, a poor governor and a worse general, executed by Cao Cao for his tongue.',
  'Gongsun Zan': 'Master of the White Horse cavalry on the northern frontier; fought Yuan Shao for a decade and burned himself in his tower at the end.',
  'Ma Teng': 'Half-Qiang lord of the far west, a giant of a man, executed with his household when Cao Cao grew tired of his sons.',
  'Liu Biao': 'Scholarly, cautious and rich, he kept Jing Province out of the wars for eighteen years and left it to a son who could not hold it.',
  'Liu Zhang': 'Weak governor of Shu who invited Liu Bei in to protect him and lost his province to his guest.',
  'Yuan Shu': 'Yuan Shao\u2019s arrogant half-brother, who got the Imperial Seal from Sun Ce, declared himself Emperor, and died begging for honey water.',
  'Zhang Lu': 'Third master of the Way of the Celestial Masters, who ruled Hanzhong as a theocracy for thirty years and surrendered to Cao Cao with dignity.',
  'Meng Huo': 'King of the Nanman, captured and released seven times by Zhuge Liang until he swore never to rebel again.',
  'Tadun': 'Great chieftain of the Wuhuan, ally of the Yuans, killed by Zhang Liao\u2019s charge at White Wolf Mountain in 207.',
  'Kebineng': 'The Xianbei chieftain who united the steppe tribes and raided the Wei frontier for thirty years until Wei sent an assassin.',
  'Diaochan': 'The beauty of Wang Yun\u2019s household, promised to both Dong Zhuo and L\u00fc Bu to set one against the other.',
  'Cao Pi': 'Cao Cao\u2019s heir, a poet and critic who deposed the last Han emperor in 220 and reigned as the first Emperor of Wei.',
  'Jiang Wei': 'A Wei officer captured and adopted by Zhuge Liang, who spent the rest of his life leading Shu\u2019s hopeless campaigns north.',
  'Deng Ai': 'A stammering clerk who became Wei\u2019s finest general and marched through the mountains to take Chengdu in 263.',
};
const CITY_NOTES = {
  longxi: 'Didao on the Tao, the western marches where Han Sui and Ma Teng raised the Liang rebellion.',
  wudu: 'The Bailong valley between Tianshui and Hanzhong, crossed by every northern campaign of Shu.',
  hedong: 'Anyi on the salt lake of the Fen valley, Guan Yu\u2019s home country and the ford across the Yellow River.',
  shangdang: 'The Taihang plateau above Ye, a fortress commandery that guards the passes into Hebei.',
  pengcheng: 'Capital of Xu Province and Tao Qian\u2019s seat, sacked by Cao Cao in 193.',
  guangling: 'The north bank of the Yangtze mouth, Chen Deng\u2019s seat and the bridgehead against Jiangdong.',
  danyang: 'Hill country south of the river whose hard men filled the Sun family\u2019s armies.',
  lingling: 'The fourth of the southern commanderies of Jing, on the upper Xiang beyond Changsha.',
  zangke: 'The Nanzhong hills between Yi and the south, where the Zangke river runs toward the sea.',
  hepu: 'The pearl coast on the Gulf of Tonkin, the sea road between Nanhai and Jiaozhi.',
  jianan: 'Minzhong behind its mountains, Shanyue country where Wang Lang fled and He Qi later campaigned.',
  donglai: 'The tip of the Shandong peninsula, Taishi Ci’s home at the end of the peninsula road.',
  luoyang: 'The eastern capital of the Han, burned by Dong Zhuo in 190 and never the same again.',
  changan: 'The western capital, seat of the court after 190, wrecked by the feuds of Dong Zhuo\u2019s generals.',
  xuchang: 'Cao Cao\u2019s capital from 196, where the puppet Emperor lived out his reign.',
  ye: 'Capital of Ji Province and of Yuan Shao, later Cao Cao\u2019s seat as Duke of Wei.',
  chenliu: 'Where Cao Cao first raised troops against Dong Zhuo.',
  puyang: 'Seat of Dong Commandery, prize of the war between Cao Cao and L\u00fc Bu.',
  xiapi: 'Capital of Xu Province; Liu Bei\u2019s, then L\u00fc Bu\u2019s, where he died at the White Gate.',
  xiaopei: 'The small town where Liu Bei twice took refuge.',
  xiangyang: 'Capital of Jing Province, key to the middle Yangtze.',
  jiangling: 'The great river fortress, fought over by Cao Cao, Zhou Yu, Guan Yu and L\u00fc Meng.',
  jiangxia: 'Where Sun Jian died and where Liu Bei fled before Red Cliffs.',
  chaisang: 'Zhou Yu\u2019s fleet base and the anchorage of the Sun before Red Cliffs.',
  jianye: 'Sun Quan\u2019s capital, the future Nanjing, built to rule the Yangtze.',
  wu: 'Heartland of the Sun family and the old Wu kingdom.',
  chengdu: 'Capital of Shu in the Land of Abundance, Liu Bei\u2019s at last in 214.',
  hanzhong: 'Zhang Lu\u2019s theocracy, then the gateway between Shu and Wei, won by Liu Bei in 219.',
  guandu: '', jinyang: 'Seat of Bing Province, the frontier against the Xianbei.',
  beiping: 'Gongsun Zan\u2019s fortress on the northern frontier.',
  xiangping: 'Seat of the Gongsun family\u2019s independent realm in Liaodong.',
  liucheng: 'Seat of the Wuhuan chieftains until Cao Cao\u2019s campaign of 207.',
  danhan: 'Where Tanshihuai once held court over all the Xianbei.',
  jianning: 'Nanman country, where Zhuge Liang campaigned in 225.',
  jiaozhi: 'The far south, ruled for forty years by the Shi family.',
  changsha: 'Sun Jian\u2019s first command and later Liu Bei\u2019s southern base.',
  shouchun: 'Yuan Shu\u2019s capital, where he proclaimed himself Emperor.',
  wan: 'Nanyang, the empire\u2019s richest commandery, and the site of Zhang Xiu\u2019s night attack.',
  xinye: 'Liu Bei\u2019s border post for seven years, where he recruited Zhuge Liang.',
  yongan: 'Baidicheng, where Liu Bei died after Yiling.',
  hongnong: 'Tong Pass, the gate between the two capitals.',
};

// Historical flavour shown at the start of certain months.
const HISTORY_NOTES = {
  '190-1': 'The lords of the east gather at Suanzao against Dong Zhuo.',
  '190-4': "Dong Zhuo burns Luoyang and drags the court west to Chang'an.",
  '191-1': 'Sun Jian finds the Imperial Seal in the ruins of Luoyang.',
  '192-4': "Wang Yun's plot: Lü Bu turns on Dong Zhuo.",
  '194-1': "Cao Cao avenges his father in Xu Province; Liu Bei comes to Tao Qian's aid.",
  '196-1': 'Cao Cao brings the Emperor to Xuchang.',
  '200-1': 'The great clash at Guandu approaches.',
  '208-1': 'Rumours of a great battle to come on the Yangtze at Red Cliffs.',
};
